### ISSUE TITLE
If $install_method = 'url', won't upgrade consul

### ISSUE THREAD

**Issue by EvanKrall** [solarkennedy/puppet-consul#103]
I have to manually remove both /usr/local/bin/consul and /opt/staging/consul/consul.zip to get this module to upgrade Consul.

**Comment by split3** [comment]
Yea this one has to do with the filename that is being set with the staging module.  It is writing it to `consul.zip` as you see.  Same goes for the UI as well.

Given the upgrade instructions by Consul:
1. On each server, install version B of Consul.
2. Shut down version A, restart with version B.
3. Once all the servers are upgraded, begin a rollout of clients following the same process.
4.Done! You are now running the latest Consul agent. You can verify this by running consul members to make sure all members have the latest build and highest protocol version.

We'd probably need to detect that an upgrade was happening before automatically replacing the binary (though that would still probably work to just replace and issue a restart)

**Comment by split3** [comment]
This should now be resolved via #202
