### ISSUE TITLE
delete_undef_values required stdlib 4.2.0, dependency not set properly

### ISSUE THREAD

**Issue by zxjinn** [solarkennedy/puppet-consul#109]
Hey guys, first of all: I appreciate all the hard work you're doing here, this module is great.

I noticed a small problem when pulling from master (specifically I'm working off of: 0bbbea631780b284d36dff955716adab8c0652e0). When pulling the module via librarian-puppet it checks the dependencies in the [metadata.json](metadata.json) file. I currently have puppetlabs-stdlib 4.1.0 installed, which passed the dependency check in the metadata.json file, because that file claims your module only requires puppetlabs-stdlib version 0.1.6 or greater. However, a the new function delete_undef_values introduced in [this commit](cce035cbc59df5a410948e287f3637870b819bec) requires at least puppetlabs-stdlib 4.2.0.

It seems that the metadata.json file needs to be updated to reflect that fact. I can submit a PR if you desire, I'm more than willing to do that.

Thanks!

**Comment by solarkennedy** [comment]
Ah! Yes please, I did not realize that function was only available in 4.2.0 or later. Please yes a PR.
