### ISSUE TITLE
README for consul::service is out of date

### ISSUE THREAD

**Issue by zxjinn** [solarkennedy/puppet-consul#110]
In the README the `Service Definition` section code example looks like it's showing an older way of configuration. The redis example should look like so:
```puppet
  ::consul::service { 'redis':
    checks  => [
      { 
        script   => "/usr/local/bin/check_redis.py",
        interval => "10s"
      }
    ],
    port    => 8000,
    tags    => ['master']
  }
```

Just like my other issue I just made, I'm more than willing to submit a PR if you don't want to do the legwork.

**Comment by solarkennedy** [comment]
Yes please, I would love a PR on a README refresh.
If you are in there, feel free to address https://github.com/solarkennedy/puppet-consul/issues/97 ?
