### ISSUE TITLE
Hash of downloaded binary never verified

### ISSUE THREAD

**Issue by centromere** [solarkennedy/puppet-consul#116]
When installing from a URL, the hash of the file is never verified. This would be a really nice feature to have.

**Comment by solarkennedy** [comment]
Hmmm. Are you looking for security or just integrity?

**Comment by centromere** [comment]
Both.

**Comment by solarkennedy** [comment]
I think that would be best served in a non-consul specific way inside the module we use to download and unzip the thing:
https://github.com/nanliu/puppet-staging

It could take some sort of verification url?

```puppet
staging::deploy { 'the zip':
  source => download_url,
  target => target_dir,
  creates => consul,
  verfication_url => "https://dl.bintray.com/mitchellh/consul/${version}_SHA256SUMS?direct",
  verification_method => "sha256sum",
}
```

**Comment by centromere** [comment]
There's a module called [puppet-archive](https://github.com/camptocamp/puppet-archive) which has checksum verification built in.

**Comment by solarkennedy** [comment]
Ooo!!

**Comment by solarkennedy** [comment]
We now use puppet-archive, so I would accept a PR that enables verification.

**Comment by solarkennedy** [comment]
We are now officially using the latest version of puppet-archive, so this is *actually* possible if someone wants to try.

https://github.com/voxpupuli/puppet-archive#archive

With `checksum_verify` and related options for pointing the module at the right checksum url.
