### ISSUE TITLE
GOMAXPROCS discarded by upstart init due to sudo's env_reset option

### ISSUE THREAD

**Issue by bdellegrazie** [solarkennedy/puppet-consul#126]
Hi,

In upstart init version GOMAXPROCS is set correctly but then the actual consul-agent process is started via sudo.
In Ubuntu the default sudo configuration has env_reset configured and GOMAXPROCS is not part of the env_keep configuration.
I'd suggest adding a default for the consul user which has GOMAXPROCS as part of env_keep configuration to avoid it being ignored.

**Comment by bdellegrazie** [comment]
Another alternative is to drop the requirement for using sudo and instead use either /bin/su or setuid and setgid for later versions of upstart.

**Comment by solarkennedy** [comment]
Arg. I would be down for an alternative to sudo.
