### ISSUE TITLE
Ruby 1.8 support

### ISSUE THREAD

**Issue by solarnz** [solarkennedy/puppet-consul#148]
Ruby 1.8 isn't supported at the moment, as within https://github.com/solarkennedy/puppet-consul/blob/master/lib/puppet/parser/functions/consul_validate_checks.rb, it is trying to call 'Puppet::ParseError' as a function. Which results in 

```
undefined method `ParseError' for Puppet:Module at /etc/puppet/ext_modules/consul/manifests/service.pp:36 on node ip-172-18-0-234.ec2.internal
```

It appears that I can fix this by using `raise(Puppet::ParseError, 'message')` rather than `raise Puppet::ParseError('message')`, however I'm not a ruby developer so I'm not sure if this is the correct change to make or not.

Ruby 1.8 is the default ruby on Ubuntu 12.04 (which is why this is causing me issues). Would you be interested in a patch to fix support for 1.8 on this system configuration?

**Comment by solarkennedy** [comment]
Totally! One of the hardest problems is ensuring that "json" is available.

We don't currently have 1.8 supported in the matrix:
https://github.com/solarkennedy/puppet-consul/blob/master/.travis.yml

So if you can make changes that make it support 1.8 and not break forwards compatibility, go for it!
