### ISSUE TITLE
Staging missing dependency on `Package['unzip']`

### ISSUE THREAD

**Issue by jhance** [solarkennedy/puppet-consul#164]
For obvious reasons this package is needed. It doesn't seem like staging itself manages this (since it doesn't manage the `unzip` package), so consul should manage this dependency if it is managing the `unzip` package (ie, on non-darwin).

It should be sufficient (probably better) only to supply this to the files that consul itself downloads. For myself I am currently using `Package['unzip'] -> Staging::File <| |>` as a workaround.

**Comment by solarkennedy** [comment]
On `install.pp:19` we do this, so I think we are covered. Or are you asking for the package unzip to be chain ordered before we try to unzip the file?

**Comment by aj-jester** [comment]
> Or are you asking for the package unzip to be chain ordered before we try to unzip the file?

I think thats what he means. Should be a simple fix, I can work on this sometime today.

**Comment by jhance** [comment]
> I think thats what he means. Should be a simple fix, I can work on this sometime today.

Yes, thats what I mean. And yeah, this is pretty simple.

**Comment by aj-jester** [comment]
PR https://github.com/solarkennedy/puppet-consul/pull/166
