### ISSUE TITLE
Validate and document all params that could be passed to ::consul

### ISSUE THREAD

**Issue by aj-jester** [solarkennedy/puppet-consul#170]
The documentation on what params we could pass is kinda lacking. I think we should document all of the params (most are missing right now) and perhaps update the readme as well.

Also, while doing this we need to ensure these params are properly validated, that is also lacking, only a few are being validated.

I can work on this but if someone else wants to feel free and let me know if I can help :+1:

**Comment by solarkennedy** [comment]
This was solved by @tdevelioglu in #278
