### ISSUE TITLE
Log rotation?

### ISSUE THREAD

**Issue by pforman** [solarkennedy/puppet-consul#182]
Something I noticed while working in the ```sysv``` startup script is that the output is redirected into ```/var/log/consul```, but there isn't any way provided to rotate that file.

This is also the case in the `sles` script.

Should there be a logrotate.d file included?  Is this something considered outside the scope of the module?

If it's outside the scope, then feel free to close this issue.

**Comment by solarkennedy** [comment]
I consider this outside the scope of the module. (I recommend making a "profile_consul" and combining modules together in there) I use this one in production: https://github.com/rodjek/puppet-logrotate
