### ISSUE TITLE
ensure_packages unzip with 'before' breaks interoperability

### ISSUE THREAD

**Issue by ilyash-p** [solarkennedy/puppet-consul#187]
In `install.pp` there is

    ensure_packages(['unzip'], { 'before' => Staging::File['consul.zip'] })

which breaks interoperability since if you have

    ensure_packages(['unzip'])

in any other place it's a redeclaration error (because attributes are different). Minimal code that shows similar problem:

    puppet apply -e 'ensure_packages(["unzip"]) ensure_packages(["unzip"], {stage=>"main"})'

Output excerpt:

    Error: Duplicate declaration: Package[unzip] is already declared

**Comment by ilyash-p** [comment]
Possible solution: "Remove management of unzip package" - https://github.com/danieldreier/puppet-consul/commit/8253cba01dd19e0478072425a1795cbdeb1b0aa4

**Comment by solarkennedy** [comment]
Fixed by #185

**Comment by split3** [comment]
Closing since this is fixed.

**Comment by Cinderhaze** [comment]
There is another solution. (just ran into this in my copy of 1.0.2)

If you put the relationship after the ensure_packages, it can work without breaking other ensure_packages.
```puppet
ensure_package('unzip')
Package['unzip'] -> Staging::File['consul.zip']
```
This allows you to still ensure that the package is managed, but doesn't cause a Duplicate Declaration error.  I'm guessing it's similar to the 
```puppet
include 'myclass'
```
vs
```puppet
class:{'myclass':}
```
schematics.

**Comment by solarkennedy** [comment]
That will still cause the duplication error if another user declares (not via ensure_packages) `unzip` before `consul` is parsed.
