### ISSUE TITLE
metadata.json - needs at least 4.6.0 of stdlib

### ISSUE THREAD

**Issue by gdhbashton** [solarkennedy/puppet-consul#190]
Hi,

Using 1.0.2 of the module on the Forge, the `metadata.json` specifies at least 4.2.0 of `puppetlabs/stdlib` but you're using `validate_integer` in `manifests/init.pp:100` and that feature only came in at `stdlib` version 4.6.0

https://github.com/solarkennedy/puppet-consul/blob/master/metadata.json#L14

https://forge.puppetlabs.com/puppetlabs/stdlib/changelog#2015-04-14---supported-release-460

**Comment by solarkennedy** [comment]
Ah! Do you feel comfortable making a PR to fix?

**Comment by gdhbashton** [comment]
Heh, sure PR #191  - I guess it's still easier to press 'Merge' than to edit + commit a 1-byte change ;)
