### ISSUE TITLE
Add Support for Windows

### ISSUE THREAD

**Issue by hopperd** [solarkennedy/puppet-consul#195]
Adding this issue for tracking, my company will be working on providing this support as we have hundreds of windows boxes that will need this support.

**Comment by brettswift** [comment]
We're looking for this as well.  Our numbers would be at least a hundred, potentially quite a bit more.

If you guys want some early testing let me know.

**Comment by brettswift** [comment]
@split3  curious - are you guys using chocolatey?   https://chocolatey.org/packages/consul

**Comment by split3** [comment]
We aren't, we have the windows support initially written entirely in puppet, just needs some tightening up and polish.

**Comment by split3** [comment]
We will need to replace the staging module with archive to provide support for windows.  This initial work is already completed by #243

**Comment by split3** [comment]
Initial code for this (work in progress) has been posted to the following branch:

[https://github.com/solarkennedy/puppet-consul/tree/feature/windows_support](url)

Still quite a bit of work like tests, nssm optional usage (defaulting to sc for management, etc)

**Comment by wmuizelaar** [comment]
Would love to have chocolatey support as well - is there a way I can contribute?

**Comment by ferventcoder** [comment]
@split3 @wmuizelaar +1 on chocolatey support.

~~~puppet
package {'consul':
  ensure => latest|version|installed|held,
  provider => chocolatey,
  source => 'internal source',
}
~~~

Here's the package fully ready to rock - https://chocolatey.org/packages/consul

We always suggest hosting your own internal packages on an internal package server when you are using Chocolatey for production purposes. You will see this package is ready to go already since it doesn't download any external resources, so it won't need any recompiling (downloading and internalizing resources). The moderator (me in this case) verified the checksums with the original shas from the hashicorp site.

**Comment by ferventcoder** [comment]
Forgot to mention, there is a download link on the left side.

**Comment by split3** [comment]
The feature branch that has this work is located here:

https://github.com/solarkennedy/puppet-consul/tree/feature/windows_support

Feel free to work from that to add the chocolatey support if desired.  I'm curious though, what value does chocolatey add that isn't covered by the module itself?

**Comment by ferventcoder** [comment]
Based on your description, you offer install by url or by package - Chocolatey would be the by package route for Windows.

Lots of work went into that feature branch, and packaging could give you a second option without much more effort. One could use the consul package from https://chocolatey.org and offer the option to override that with an internal package.

**Comment by solarkennedy** [comment]
We are cut over to puppet-archive (officially) now 100%.

I would be down for either installation approach, it doesn't have to be perfect the first time.

**Comment by claflico** [comment]
We want to use this module for managing Windows as well. Anything we can do to get the ball rolling on this again?

**Comment by ferventcoder** [comment]
@solarkennedy From what I can see, you are already set up to support the Chocolatey package - https://github.com/solarkennedy/puppet-consul/blob/132a80cf64b9351a036f0baa5c2382f723a5c1cd/manifests/install.pp#L82-L84. Once the url route bits are accepted, there may not be much else that needs to change. Would need some testing.

**Comment by solarkennedy** [comment]
Yea, and it is totally ok to release windows support as "experimental".

Do you want me to merge this as is? https://github.com/solarkennedy/puppet-consul/compare/feature/windows_support

Or does anyone have a fork that works that they can PR?

**Comment by ferventcoder** [comment]
@solarkennedy that code looks mostly good to me. I'd only suggest as an enhancement to do similar to Puppet to find ProgramData.
Code in question - https://github.com/solarkennedy/puppet-consul/compare/feature/windows_support#diff-01eea9f59a7a7e8a90b87b99336e4cfbR5

Could do something like:
https://github.com/puppetlabs/puppet/blob/d00d0b7d34a211f59c5c58d0404e7b126681c2e8/install.rb#L258 and https://github.com/puppetlabs/puppet/blob/d00d0b7d34a211f59c5c58d0404e7b126681c2e8/install.rb#L253

You are at least guaranteed that the win32-dir gem is loaded with Puppet in the interim. 

On second thought, maybe leave that the way it is. 👍

**Comment by hopperd** [comment]
I know this code was used in production at my previous company for quite some time. Though it obviously hasn't been kept up2date and could probably use a little polish.

**Comment by solarkennedy** [comment]
I will rubber stamp any Windows support PR. I don't personally run Windows so I'll have to lean on community support for real-world testing.

**Comment by claflico** [comment]
We're just getting started with consul and I hacked some code to wrap around your Linux code to make it work on Windows so I should be able to provide some decent testing.

**Comment by krjensen** [comment]
Any change that this will picked up again, so we could use windows?

**Comment by solarkennedy** [comment]
Beta support is now released.
