### ISSUE TITLE
Consul reload fails when rpc_addr is 0.0.0.0

### ISSUE THREAD

**Issue by danielbenzvi** [solarkennedy/puppet-consul#220]
Hey
The reload_service class is trying to reload the consul service by explicitly specifying the rpc addr and port.
While this makes perfect sense in case non default ports are used, it fails when the rpc_addr was set to listen to 0.0.0.0. 

```
  if $consul::manage_service == true and $consul::service_ensure == 'running' {
    exec { 'reload consul service':
      path        => [$consul::bin_dir,'/bin','/usr/bin'],
      command     => "consul reload -rpc-addr=${consul::rpc_addr}:${consul::rpc_port}",
      refreshonly => true,
    }
  }
```

**Comment by solarkennedy** [comment]
Ah gotcha. @danielbenzvi can you make a PR to just connect to localhost instead if the rpc addr is `0.0.0.0`?
