### ISSUE TITLE
Duplicate declaration: Class[Staging] with puppet/mysql mysqltuner

### ISSUE THREAD

**Issue by luckyraul** [solarkennedy/puppet-consul#223]

**Comment by bflad** [comment]
Hmmm, this module is using `include staging` which should not cause duplicate declaration:
https://github.com/solarkennedy/puppet-consul/blob/master/manifests/install.pp#L18

While `mysql::server::mysqltuner` uses a hard class declaration:
https://github.com/puppetlabs/puppetlabs-mysql/blob/master/manifests/server/mysqltuner.pp#L31-L35

They might be able to fix the mysql module to use `include staging` as well or use the top scope for the class resource `class { '::staging': ... }`

**Comment by luckyraul** [comment]
created issue there.

**Comment by luckyraul** [comment]
thanks

**Comment by solarkennedy** [comment]
Yea, not a great situation. The only other option I would like to provide is that you could ensure that `mysql` is *parsed* before `consul`, but parse-dependent puppet code sucks.

**Comment by luckyraul** [comment]
They accepted issue.
