### ISSUE TITLE
Encryption

### ISSUE THREAD

**Issue by luckyraul** [solarkennedy/puppet-consul#224]
Is this supported https://www.consul.io/docs/agent/encryption.html ?

**Comment by bflad** [comment]
We use the `encrypt` configuration in our config_hash and it starts up with gossip encryption without issue in our setup. Our hiera looks like:

```
consul::config_hash:
...
  encrypt: ourkeygenvalue
...
```

As for automatically generating that value for the configuration, I'm not sure that's something that can be done here at the moment.

**Comment by luckyraul** [comment]
thanks
