### ISSUE TITLE
Question : Atlas join

### ISSUE THREAD

**Issue by CruzanCaramele** [solarkennedy/puppet-consul#228]
One of the features of Consul is to view the state of your infrastructure on Atlas . Is there a way to configure your infrastructure using this module to have it display the state of the infrastructure on Atlas ?

**Comment by solarkennedy** [comment]
https://www.consul.io/docs/guides/atlas.html

Using arbitrary option in `config_hash`, looks like you can do this. Looks like it would probably be better for us to support the `ATLAS_TOKEN` env variable so you don't see it in the cli flags in ps.

PRs welcome for a readme update or any changes needed to make this work! AFAIK nobody has done it yet.

**Comment by brainonmute** [comment]
I was wondering what the syntax is for this then. I am unable to use the config hash as follows:

```
class { '::consul':
  config_hash => {
    'bootstrap_expect' => 1,
    'data_dir'         => '/opt/consul',
    'datacenter'       => 'east-aws',
    'log_level'        => 'INFO',
    'node_name'        => 'server',
    'server'           => true,


  }
}
```

**Comment by brainonmute** [comment]
I would love to do this and have been testing it. I may be missing something basic here.

```
  class { '::consul':
  version     => $consul_version,
  config_hash => {
    'data_dir'    => '/opt/consul',
    'datacenter'  => $consul_datacenter,
    'log_level'   => 'INFO',
    'node_name'   => $::fqdn,
    'retry_join'  => $consul_servers,
    'encrypt'     => $consul_encryption_key,
    'atlas'       => 'username/environment',
    'atlas-token' => 'example24345563123' ,
    }
  }
```

Doesn't seem to work. I can use the same settings to start the agent manually (passing agent options inline). When I use the above, I get 

```
consul agent -config-dir /etc/consul/
==> Error decoding '/etc/consul/config.json': Config has invalid keys: atlas,atlas-token
```

Any ideas?

**Comment by solarkennedy** [comment]
You need to use the correct keys: https://www.consul.io/docs/agent/options.html#atlas_infrastructure

This is part of the config hash, they are not command line options.

**Comment by brainonmute** [comment]
Thank you, that was it.
