### ISSUE TITLE
Service start is broken on Debian > 8.0

### ISSUE THREAD

**Issue by albustax** [solarkennedy/puppet-consul#232]
Hello,

On Debian 8.2, (and 8.x globally), catalogue compilation is broken with this message:

```
Error: /Stage[main]/Consul::Run_service/Service[consul]: Could not evaluate: Could not find init script for 'consul'
Notice: /Stage[main]/Consul::Reload_service/Exec[reload consul service]: Dependency Service[consul] has failures: true
Warning: /Stage[main]/Consul::Reload_service/Exec[reload consul service]: Skipping because of failed dependencies
Notice: /Stage[main]/Consul/Anchor[consul_last]: Dependency Service[consul] has failures: true
Warning: /Stage[main]/Consul/Anchor[consul_last]: Skipping because of failed dependencies
```

Puppet try to launch the service with `init` because `provider`is not set on [service declaration](https://github.com/solarkennedy/puppet-consul/blob/7ba8c2460f06245f6ba6e64a90f1446ead611882/manifests/run_service.pp#L14)

This is a bug with the puppet provider, for more informations, see [this bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=775795)

**2 workarounds are possible**:

- Dirty method -> configure service globally

```
  Service { provider => 'systemd'}

  class { '::consul':
    config_hash => {
      'bootstrap_expect' => 1,
      'data_dir'         => '/opt/consul',
      'datacenter'       => 'eu-west-1',
      'log_level'        => 'INFO',
      'node_name'        => "${::fqdn}",
      'server'           => true,
    }
  }
```
- Clean method -> change module behaviour

Add a switchcase on [service declaration](https://github.com/solarkennedy/puppet-consul/blob/7ba8c2460f06245f6ba6e64a90f1446ead611882/manifests/run_service.pp#L14) and set `provider`if necessary.

**For informations**:

puppet-client version: `3.8.6-1puppetlabs1`
puppetmaster version:  `3.8.6-1puppetlabs1`
debian version: `8.2`

**Comment by solarkennedy** [comment]
Can you make a PR to make it work on the platform you use?
The code hint is probably here:
https://github.com/solarkennedy/puppet-consul/blob/3e43a74949df1ff9892f93ac5deb2a8fdc9d6362/manifests/params.pp#L52

**Comment by bdronneau** [comment]
Hey, this not the PR https://github.com/solarkennedy/puppet-consul/pull/125 ?

**Comment by albustax** [comment]
:+1:

**Comment by solarkennedy** [comment]
I've merge #125. Please try master.

**Comment by bdronneau** [comment]
with your last commit, puppet is able to start consul :+1:
