### ISSUE TITLE
Error while trying to create user consul... due group already exists

### ISSUE THREAD

**Issue by brahama** [solarkennedy/puppet-consul#236]
Could not create user consul: Execution of '/usr/sbin/useradd -M -r consul' returned 9: useradd: group consul exists - if you want to add this user to that group, use -g

Just tried and removed the group to see if that perhaps already existed, but same issue as group is created first.

**Comment by brahama** [comment]
Yes, it can be bypassed by the manage_group to false. But seems to me its not that tidy perhaps.

Cheers!

**Comment by solarkennedy** [comment]
Ah. Seems like we should be ordering the group before the user in the install.pp. Can you make a PR?

**Comment by Cinderhaze** [comment]
From what I understood, users should autorequire groups if they are declared in the same manifest.. I may be mistake though

**Comment by solarkennedy** [comment]
Yea, but only primary group (gid) and that is what #247 solves.

If you care about this issue, would you like to rebase #247 so it passes tests and applies on master?
