### ISSUE TITLE
Failed to start Raft: permission denied

### ISSUE THREAD

**Issue by joshuaspence** [solarkennedy/puppet-consul#237]
33a72c3701e52e90b50ffae01e45316dd1f5631a seemed to break things for me. After updating the puppet module to 1.0.5, the `consul` service refuses to start. In the error logs, I see this:

```
==> Error starting agent: Failed to start Consul server: Failed to start Raft: open /mnt/consul/raft/raft.db: permission denied
```

Running `sudo chown -R consul:consul /mnt/consul` seems to fix the issue.

**Comment by solarkennedy** [comment]
We have the data_dir setting:
https://github.com/solarkennedy/puppet-consul/blob/85de0cde707f2c011754677c097c53e61e66e664/manifests/install.pp#L8

Is that set?

**Comment by joshuaspence** [comment]
Yes, it is set to `/mnt/consul`

**Comment by solarkennedy** [comment]
Ah I see. But we don't recurse. 

Yea this is going to be a one time chown you are going to have to do. New users will create the folder and start consul as the non-privileged user, so everything down below will be correct.
