### ISSUE TITLE
package_name and ui_package_name can't be the same

### ISSUE THREAD

**Issue by berlincount** [solarkennedy/puppet-consul#246]
We use a custom RPM with consul that has consul_ui inside already ... installing that right now is impossible, because that gives a duplicate Package[consul] resource.

**Comment by split3** [comment]
Are you providing a `$consul::ui_dir` as that is the only way that package will get installed. If you don't provide that value the package for the UI won't get installed.  If your package already combines them try not providing the `$consul::ui_dir` and see if that works.

**Comment by split3** [comment]
So looks like it wouldn't be possible to omit the `$consul::ui_dir` as that is need in the config hash for consul and is looked up that way:
[https://github.com/solarkennedy/puppet-consul/blob/master/manifests/install.pp#L49](url)

So in this case we may need to option to forcibly exclude trying to install the UI package in this particular case.

**Comment by rawleto** [comment]
@berlincount with #398 you can try to install RPMed Consul adding 'ui => true' and 'ui_dir => some_dir' options to the config_hash (please follow a link to the details: https://github.com/solarkennedy/puppet-consul#web-ui).

**Comment by berlincount** [comment]
Ah well, I've moved on from Puppet ...
