### ISSUE TITLE
nanliu-staging dependency 

### ISSUE THREAD

**Issue by blsmth** [solarkennedy/puppet-consul#250]
is there an explicit need for this dependency? 

That module is not compatible with Puppet >= 4.0.   It's blocking me from using puppet-consul in a Puppet 4 environment.

**Comment by split3** [comment]
That dependency was recently removed and shouldn't be present in the master branch currently and you could test.  We haven't cut a release since that merged was done.

**Comment by solarkennedy** [comment]
I'll make a new release

**Comment by solarkennedy** [comment]
Go for 1.0.8 without staging.

**Comment by solarkennedy** [comment]
@blsmth additionally we have puppet 4.1.0 and 4.0.0 in .travis.yaml, so we should be compatible (or at least test against it)

**Comment by blsmth** [comment]
great, thanks @solarkennedy
