### ISSUE TITLE
Error depencie archive

### ISSUE THREAD

**Issue by xdexter** [solarkennedy/puppet-consul#253]
Hello,

Currently I use the module "Camptocamp/archive", however I can not use this module due to dependence of the module "puppet/archive" as the two have the same name I can not use both, there is a way around this problem?

Att;

**Comment by solarkennedy** [comment]
I don't know if it is going to work, but you can try it. Tell whatever tool you are using to install the module to ignore the dependencies would be the way around that.

We only test against puppet-archive.

**Comment by xdexter** [comment]
Hello @solarkennedy, I use r10k to manage the modules, but managed to solve the problem by adding a specific version of the module "KyleAnderson/consul" in case the v1.0.5, this version is not yet used the dependence of the "puppet-archive"

Thank you

**Comment by joshuaspence** [comment]
I am also facing this issue and have had to pin to version 1.0.5 as a result. Basically, I already have many modules which use camptocamp/archive and this cannot add puppet/archive. See voxpupuli/puppet-archive#165.

**Comment by solud** [comment]
Likewise this issue affects us as we use the [camptocamp/puppet-archive](https://github.com/camptocamp/puppet-archive) module. The two archive modules are not currently compatible but may be one day, according to the issue @joshuaspence linked. That effort is only just beginning but until then it seems we'll have to pin to 1.0.5 as well.
