### ISSUE TITLE
/opt/consul/serf/local.keyring is not replaced when changing encryption keys

### ISSUE THREAD

**Issue by brainonmute** [solarkennedy/puppet-consul#256]
If you run consul keygen to generate a new key, the servers and agents will not replace the local.keyring file if it already exists. If you delete local.keyring and do a Puppet apply, the problem is resolved.

The error you receive on an agent is:
`[INFO] agent: (LAN) joined: 0 Err: EOF
`
The error you receive on a server is:
`[ERR] memberlist: failed to receive: No installed keys could decrypt the message from= <ip><port>`

**Comment by solarkennedy** [comment]
Are you sure this a problem with the puppet module?
Looks similar to this upstream issue:
https://github.com/hashicorp/consul/issues/719

**Comment by brainonmute** [comment]
I believe this is the same issue.

**Comment by solarkennedy** [comment]
Ok in that case I'm going to close it in favor of that one.
