### ISSUE TITLE
Changelog on Puppetforge not updated for 1.0.9

### ISSUE THREAD

**Issue by berlincount** [solarkennedy/puppet-consul#268]
Subject says it all ;) Thanks for the great module!

**Comment by solarkennedy** [comment]
Heh. Grumble.

I need to remember to update the changelog *before* the release bump :)

I'll "Makefile" this up so I don't have to remember next time

**Comment by berlincount** [comment]
Do you have an update for me there? :)

**Comment by solarkennedy** [comment]
I've added 1.0.10 with the changelog bundled so it shows up in the forge and a make target to help me remember.
