### ISSUE TITLE
Consul service is not starting up

### ISSUE THREAD

**Issue by vopensource** [solarkennedy/puppet-consul#273]
Error: /Stage[main]/Consul::Run_service/Service[consul]: Provider init is not functional on this host

**Comment by solarkennedy** [comment]
What is your distro?

**Comment by vopensource** [comment]
RHEL 6.5

_Veeksha

**Comment by solarkennedy** [comment]
Can you confirm you are using a recent version of the module?

The default provider for RHEL6.5 should be "redhat", not init:
https://github.com/solarkennedy/puppet-consul/blob/875a336c508ddf279eb4ef36923ddfb1f324ba0b/manifests/params.pp#L41

**Comment by vopensource** [comment]
No i was not using recent version of the module, it was taking init in one
of the earlier version of the module i believe , so took the latest version
now and is working.
Thanks !
