### ISSUE TITLE
Support for puppet-archive >=1.0.0

### ISSUE THREAD

**Issue by mgla** [solarkennedy/puppet-consul#275]
The current version of puppet-archive is v1.1.1, and it _seems_ to work just fine with v.1.1.1 (I am not able to verify this). Maybe update the metadata.json to allow newer archive versions without error?

Current dependency:
```
    {
      "name": "puppet/archive",
      "version_requirement": ">=0.5.0 <1.0.0"
    }
```

**Comment by epleterte** [comment]
I hit this now as well. From puppet-librarian:

    [Librarian] Conflict between puppet-archive (< 1.0.0, >= 0.5.0) <(no source specified)> and puppet-archive/1.0.0 <https://forgeapi.puppetlabs.com>
    Could not resolve the dependencies.

I will try just allowing a newer version of the archive module.

**Comment by ghoneycutt** [comment]
Tried using puppet/archive v1.1.1 and it has syntax errors that made it unusable at all with Puppet v3.

**Comment by mgla** [comment]
@ghoneycutt Can you elaborate on the syntax errors? It works fine for me

**Comment by solarkennedy** [comment]
The only build failures in #227 are related to Puppet 3.1.0.
I'm pretty sure we have test coverage to cover all the cases where we use `archive`.

**Comment by krjensen** [comment]
Can we get this fixed soon? unable to install on Ubuntu 16.04 without this fix.

**Comment by solarkennedy** [comment]
@ghoneycutt can you look at #277? I did have to remove 3.1.0 from the matrix, the exact failure was here: https://travis-ci.org/solarkennedy/puppet-consul/jobs/155769754

The matrix on that pr still has 3.3, 3.7, and 3.8, so decent v3 coverage?

**Comment by solarkennedy** [comment]
I've release 1.1.0 of this module with this change.
