### ISSUE TITLE
Quoted integer (string) to integer is breaking tags

### ISSUE THREAD

**Issue by phyber** [solarkennedy/puppet-consul#283]
In https://github.com/solarkennedy/puppet-consul/issues/119 quoted things that look like integers are explicitly turned into integers.

This breaks if you want a tag such as `"tags": ["106"]` as now you turn this into `"tags": [106]` and `consul` will no longer start, giving the error:
`* 'Tags[0]' expected type 'string', got unconvertible type 'float64'`.

Would it be possible just target areas of the config where you know the value needs to be an int instead of blanket changing them?

Thanks.

**Comment by solarkennedy** [comment]
Hmm. Yea I guess we could either whitelist tags or "blacklist" things like `port`?
@aj-jester or @weitzj do you have any opinions?

**Comment by weitzj** [comment]
I do not have any opinion.

**Comment by solarkennedy** [comment]
@phyber I would accept a PR that whitelists `tags`, or just casts them to strings right before returning the json, as `tags` will always be an array of strings.

**Comment by wstiern** [comment]
Hi. Just throwing my lot in on this one. I don't have any code to contribute but will note this is blocking me from being able to tag certain services with their port numbers and isolate a DNS lookup to only those services, like:

```
# dig @127.0.0.1 -p 8600 <portNumber>.<serviceName>.service.<dataCenter>.consul SRV
```

Thus far my workaround is to pull the service-level SRV and filter on content since the ports are included in the answer section, but it would be nice to not have to do that. :)

Thanks for your work on this module! <3

**Comment by aj-jester** [comment]
@phyber @wstiern What happens when you try the following?

```
"tags": ["\"106\""]
```

If you do the above does it still break consul on startup?

**Comment by btsibr** [comment]
Also happens for specifying ports in the addresses configuration option.
````
addresses => {
   https => '8543'
}
````

**Comment by sts** [comment]
@solarkennedy Please get this merged, as [we are about to base the puppet consul-template](
https://github.com/claranet/puppet-consul_template/issues/100) upon `consul_sorted_json.rb`. consul-template has a `perms` configuration setting, which configures filesystem permissions eg. in the form: `0644`. `0644` is not a valid integer, but consul_sorted_json.rb still formats it as one.
