### ISSUE TITLE
Consul binary not found when puppet agent is daemonized

### ISSUE THREAD

**Issue by mspaulding06** [solarkennedy/puppet-consul#290]
Sometimes the consul binary cannot be found when resolving facts on a system.  This results in information like the consul_version fact not being available to puppet modules.  It turns out that the problem happens because the default install location of the consul binary symlink is `/usr/local/bin`.  When the puppet agent is daemonized on system start it is run by the init process which does not have `/usr/local/bin` in its path.  If puppet is run by a user with `sudo puppet agent -t` this all works fine because typically `/usr/local/bin` is in the path, but all automated runs will fail to resolve these facts.

There are a couple of possible solutions to this problem.  I didn't submit a PR because I figured it would be better to discuss what the right fix is first.  Solutions are:
1. Modify the fact so that it points to the absolute path of the consul binary (`/usr/local/bin/consul`).
2. Modify `/etc/sysconfig/puppet` on all systems to include `/usr/local/bin` in the path.

The first solution seems like it makes sense, but the problem is that the `bindir` variable in the consul module is configurable, and there is no way to read `bindir` from a custom fact.  The second solution requires a global modification to the system in order for this to work.  I guess one possible solution is it make it so that the `bindir` location is not configurable and symlink into a location that is guaranteed to exist (`/usr/bin`) instead.

**Comment by solarkennedy** [comment]
Blarg :(

`/usr/local/bin` "feels" like the right place to put a randomly downloaded file. 

As a work around you could change the bin dir:
https://github.com/solarkennedy/puppet-consul/blob/605f5a705187f5783df20a67d0eb70b978a3ae09/manifests/init.pp#L16

Also we could "hack" the path in the fact itself.

**Comment by mspaulding06** [comment]
I agree that `/usr/local/bin` "feels" like the right place.  It just, sadly, doesn't seem to work.  And I assume I'm not the only person affected by this.  It would be unfortunate to require all users of the module to set `bin_dir` in order to get facts to resolve.

When you say "hack" the path, are you referring to setting the fact's binary to use an absolute path like `/usr/local/bin/consul`?  That solution would be fine with me, just that the `bin_dir` could not be changed then.

**Comment by solarkennedy** [comment]
This is the first time this issue has been raised, but yes you are probably not the only person to be affected.

When I say "hack" I mean literally adjust the path in the environment during execution of the fact to include `/usr/local/bin/` if it ins't in there.

**Comment by mspaulding06** [comment]
Hey, that actually sounds like a pretty good solution to me.  I'd be happy to submit a patch if you're serious about the solution.

**Comment by solarkennedy** [comment]
Yea man, shipit.

**Comment by solarkennedy** [comment]
@mspaulding06 is this good to close?
