### ISSUE TITLE
Consul user is created with login shell

### ISSUE THREAD

**Issue by madAndroid** [solarkennedy/puppet-consul#293]
Hi,

We're implementing CIS compliance based on the [CIS benchmark](https://benchmarks.cisecurity.org/tools2/linux/CIS_CentOS_Linux_7_Benchmark_v2.1.0.pdf), and when we're running our InSpec profiles on servers that have consul installed via this module, the system user created for consul has a login shell set (`/bin/bash` in this case) .. would you be open to explicitly setting the shell to `/sbin/nologin`?

I'll send a PR if this is something that you're likely to accept a change for.

**Comment by solarkennedy** [comment]
Whoa. Yes please.

**Comment by solarkennedy** [comment]
Thank you for addressing this.

**Comment by madAndroid** [comment]
Thanks :)

**Comment by madAndroid** [comment]
It turns out this might be problematic :(

https://github.com/hashicorp/consul/issues/1358#issuecomment-223027340

We're now seeing health checks fail .. might be better to revert this change until the issue with consul using a login shell is fixed ... sorry for the hassle, turns out this wasn't a wise change

**Comment by solarkennedy** [comment]
Crap. Reverted :(

**Comment by madAndroid** [comment]
Sorry about that! a bit annoying that consul's using a login shell instead
of just running golang's exec... I've had to add an exception for our CIS
benchmarks for that, for now
