### ISSUE TITLE
cant use latest consul version as parameter

### ISSUE THREAD

**Issue by deepakdalavi** [solarkennedy/puppet-consul#305]
HI,

We cant specify latest consul version please guide how to specify within your manifest

**Comment by solarkennedy** [comment]
Hashicorp does not provide system packages, so you can't specify `latest`.
The current latest is 0.7.2. 

All input parameters to this module are specified in the docstrings of the manifest
https://github.com/solarkennedy/puppet-consul/blob/master/manifests/init.pp
