### ISSUE TITLE
  // , What are the valid strings for init_style? 

### ISSUE THREAD

**Issue by v6** [solarkennedy/puppet-consul#324]
// , I would assume that valid strings are the following: 

    'openrc'
    'init'
    'systemd'
    'none'

But I don't see the options here. Perhaps they're elsewhere? 

May I add these as options in a pull request to add to the comments here:

https://github.com/solarkennedy/puppet-consul/blob/0b9ad9e92992a94c9b5142af2318fd31a6e5bd0a/manifests/init.pp#L52

**Comment by solarkennedy** [comment]
Sure, yes please.
