### ISSUE TITLE
please specify json module version minimum

### ISSUE THREAD

**Issue by mleklund** [solarkennedy/puppet-consul#328]
We are running puppetserver 1.2 and the json version that was installed was not new enough.  We were getting the following error:
`Error 400 on SERVER: undefined method Exception for JSON:Module at /etc/puppet/environments/consul_update/modules/consul/manifests/config.pp:114`

Please update the README with the minimum needed json version to save some poor soul the trouble of tracing through these errors.

**Comment by solarkennedy** [comment]
That is really surprising to me. I figured any json module would do.
The readme does reference that you need "some" json module, but I wasn't aware of any particular version requirements:
https://github.com/solarkennedy/puppet-consul#limitations

What version did you have that didn't work, and then what version did you install that did?

**Comment by mleklund** [comment]
1.8.0 did not work, json-2.0.3 did, but there are many versions in between, so I am not sure which would fix it.

**Comment by mleklund** [comment]
thanks for the quick update
