### ISSUE TITLE
Consul 0.8.0 is out! and it breaks a few things...

### ISSUE THREAD

**Issue by mrwulf** [solarkennedy/puppet-consul#331]
- `-rpc-addr` no longer supported from command line so init.d script can't check status
- dc seems to be always lowercase- which makes joining the wan never fire

**Comment by solarkennedy** [comment]
That is "OK", I can make a new major release (3) that is only compatible with 0.8. Let's put `BREAKING` in the title of any PR related to this so that it is obvious from the changelog.
