### ISSUE TITLE
Execution of 'unzip -o /var/lib/consul/archives/consul-0.7.4.zip' returned 1: 

### ISSUE THREAD

**Issue by induja0107** [solarkennedy/puppet-consul#332]
Many a times, i am facing this issue while consul is getting extracted through this module. 

Raising this issue so I know if you are going to add return code 1 as acceptable return code for the Exec unzip consul. If there is an alternative solution i can use upright without needing any fix from your side, please let me know. I will go with either option. Many thanks! 

More log info:

2017-04-06 10:29:04 -0500 Puppet (err): Execution of 'unzip -o /var/lib/consul/archives/consul-0.7.4.zip' returned 1: 
2017-04-06 10:29:04 -0500 /Stage[main]/Consul::Install/Archive[/var/lib/consul/archives/consul-0.7.4.zip]/ensure (err): change from absent to present failed: Execution of 'unzip -o /var/lib/consul/archives/consul-0.7.4.zip' returned 1: 
2017-04-06 10:29:04 -0500 /Stage[main]/Consul::Install/File[/var/lib/consul/archives/consul-0.7.4/consul] (warning): Skipping because of failed dependencies

**Comment by solarkennedy** [comment]
Are you sure an error code of 1 is actually acceptable? Can you run `unzip -o /var/lib/consul/archives/consul-0.7.4.zip` yourself and paste the full output?

**Comment by induja0107** [comment]
This is what i get when i try it manually. unzip:  cannot find or open /var/lib/consul/archives/consul-0.7.4, /var/lib/consul/archives/consul-0.7.4.zip or /var/lib/consul/archives/consul-0.7.4.ZIP.

**Comment by solarkennedy** [comment]
It sounds like the unzip didn't work because the download failed? (or the zip got cleaned up after the puppet run)

Can you run puppet with --debug and paste as much output as you can?

**Comment by induja0107** [comment]
Hello, This is the complete log info 

Apr 11 11:59:42 node1 puppet-agent[2304]: (/Stage[main]/Consul_ka/Exec[restart_rsyslogd_consul]) Triggered 'refresh' from 1 events
Apr 11 11:59:42 node1 puppet-agent[2304]: (/Stage[main]/Consul_ka/Exec[mkdir -p /opt/consul]/returns) executed successfully
Apr 11 11:59:42 node1 puppet-agent[2304]: (/Stage[main]/Consul::Install/File[/opt/consul]/owner) owner changed 'root' to 'consul'
Apr 11 11:59:42 node1 puppet-agent[2304]: (/Stage[main]/Consul::Install/File[/opt/consul]/group) group changed 'root' to 'consul'
Apr 11 11:59:42 node1 puppet-agent[2304]: (/Stage[main]/Consul::Install/File[/opt/consul/archives]/ensure) created
Apr 11 11:59:42 node1 puppet-agent[2304]: (/Stage[main]/Consul::Install/File[/opt/consul/archives/consul-0.7.4]/ensure) created
Apr 11 11:59:44 node1 puppet-agent[2618]: Could not execute posix command: No such file or directory - unzip
Apr 11 11:59:44 node1 puppet-agent[2304]: Execution of 'unzip -o /opt/consul/archives/consul-0.7.4.zip' returned 1:
Apr 11 11:59:44 node1 puppet-agent[2304]: (/Stage[main]/Consul::Install/Archive[/opt/consul/archives/consul-0.7.4.zip]/ensure) change from absent to present failed: Execution of 'unzip -o /opt/consul/archives/consul-0.7.4.zip' returned 1:
Apr 11 11:59:44 node1 puppet-agent[2304]: (/Stage[main]/Consul::Install/File[/opt/consul/archives/consul-0.7.4/consul]) Dependency Archive[/opt/consul/archives/consul-0.7.4.zip] has failures: true
Apr 11 11:59:44 node1 puppet-agent[2304]: (/Stage[main]/Consul::Install/File[/opt/consul/archives/consul-0.7.4/consul]) Skipping because of failed dependencies
Apr 11 11:59:44 node1 puppet-agent[2304]: (/Stage[main]/Consul::Install/File[/usr/local/bin/consul]) Dependency Archive[/opt/consul/archives/consul-0.7.4.zip] has failures: true
Apr 11 11:59:44 node1 puppet-agent[2304]: (/Stage[main]/Consul::Install/File[/usr/local/bin/consul]) Skipping because of failed dependencies
Apr 11 11:59:44 node1 puppet-agent[2304]: (/Stage[main]/Consul::Config/File[/lib/systemd/system/consul.service]) Dependency Archive[/opt/consul/archives/consul-0.7.4.zip] has failures: true
Apr 11 11:59:44 node1 puppet-agent[2304]: (/Stage[main]/Consul::Config/File[/lib/systemd/system/consul.service]) Skipping because of failed dependencies
Apr 11 11:59:44 node1 puppet-agent[2304]: (/Stage[main]/Consul::Config/Exec[consul-systemd-reload]) Dependency Archive[/opt/consul/archives/consul-0.7.4.zip] has failures: true
Apr 11 11:59:44 node1 puppet-agent[2304]: (/Stage[main]/Consul::Config/Exec[consul-systemd-reload]) Skipping because of failed dependencies
Apr 11 11:59:44 node1 puppet-agent[2304]: (/Stage[main]/Consul::Config/File[/etc/consul]) Dependency Archive[/opt/consul/archives/consul-0.7.4.zip] has failures: true
Apr 11 11:59:44 node1 puppet-agent[2304]: (/Stage[main]/Consul::Config/File[/etc/consul]) Skipping because of failed dependencies
Apr 11 11:59:44 node1 puppet-agent[2304]: (/Stage[main]/Consul::Config/File[consul config.json]) Dependency Archive[/opt/consul/archives/consul-0.7.4.zip] has failures: true
Apr 11 11:59:44 node1 puppet-agent[2304]: (/Stage[main]/Consul::Config/File[consul config.json]) Skipping because of failed dependencies
Apr 11 11:59:44 node1 puppet-agent[2304]: (/Stage[main]/Consul_ka/Exec[clean invalid consul data]) Dependency Archive[/opt/consul/archives/consul-0.7.4.zip] has failures: true
Apr 11 11:59:44 node1 puppet-agent[2304]: (/Stage[main]/Consul_ka/Exec[clean invalid consul data]) Skipping because of failed dependencies
Apr 11 11:59:44 node1 puppet-agent[2304]: (/Stage[main]/Consul::Run_service/Service[consul]) Dependency Archive[/opt/consul/archives/consul-0.7.4.zip] has failures: true
Apr 11 11:59:44 node1 puppet-agent[2304]: (/Stage[main]/Consul::Run_service/Service[consul]) Skipping because of failed dependencies
Apr 11 11:59:44 node1 puppet-agent[2304]: (/Stage[main]/puppet_agent_run/File[/opt/cdtest/bin/execute-puppet.sh]/ensure) defined content as '{md5}9338f0e1238b4b2b60bb19493799aa36'

**Comment by induja0107** [comment]
Hello, this is the complete log info.

Apr 11 11:59:42 node1 puppet-agent[2304]: (/Stage[main]/Consul_mod/Exec[restart_rsyslogd_consul]) Triggered 'refresh' from 1 events
Apr 11 11:59:42 node1 puppet-agent[2304]: (/Stage[main]/Consul_mod/Exec[mkdir -p /opt/consul]/returns) executed successfully
Apr 11 11:59:42 node1 puppet-agent[2304]: (/Stage[main]/Consul::Install/File[/opt/consul]/owner) owner changed 'root' to 'consul'
Apr 11 11:59:42 node1 puppet-agent[2304]: (/Stage[main]/Consul::Install/File[/opt/consul]/group) group changed 'root' to 'consul'
Apr 11 11:59:42 node1 puppet-agent[2304]: (/Stage[main]/Consul::Install/File[/opt/consul/archives]/ensure) created
Apr 11 11:59:42 node1 puppet-agent[2304]: (/Stage[main]/Consul::Install/File[/opt/consul/archives/consul-0.7.4]/ensure) created
Apr 11 11:59:44 node1 puppet-agent[2618]: Could not execute posix command: No such file or directory - unzip
Apr 11 11:59:44 node1 puppet-agent[2304]: Execution of 'unzip -o /opt/consul/archives/consul-0.7.4.zip' returned 1:
Apr 11 11:59:44 node1 puppet-agent[2304]: (/Stage[main]/Consul::Install/Archive[/opt/consul/archives/consul-0.7.4.zip]/ensure) change from absent to present failed: Execution of 'unzip -o /opt/consul/archives/consul-0.7.4.zip' returned 1:
Apr 11 11:59:44 node1 puppet-agent[2304]: (/Stage[main]/Consul::Install/File[/opt/consul/archives/consul-0.7.4/consul]) Dependency Archive[/opt/consul/archives/consul-0.7.4.zip] has failures: true
Apr 11 11:59:44 node1 puppet-agent[2304]: (/Stage[main]/Consul::Install/File[/opt/consul/archives/consul-0.7.4/consul]) Skipping because of failed dependencies
Apr 11 11:59:44 node1 puppet-agent[2304]: (/Stage[main]/Consul::Install/File[/usr/local/bin/consul]) Dependency Archive[/opt/consul/archives/consul-0.7.4.zip] has failures: true
Apr 11 11:59:44 node1 puppet-agent[2304]: (/Stage[main]/Consul::Install/File[/usr/local/bin/consul]) Skipping because of failed dependencies
Apr 11 11:59:44 node1 puppet-agent[2304]: (/Stage[main]/Consul::Config/File[/lib/systemd/system/consul.service]) Dependency Archive[/opt/consul/archives/consul-0.7.4.zip] has failures: true
Apr 11 11:59:44 node1 puppet-agent[2304]: (/Stage[main]/Consul::Config/File[/lib/systemd/system/consul.service]) Skipping because of failed dependencies
Apr 11 11:59:44 node1 puppet-agent[2304]: (/Stage[main]/Consul::Config/Exec[consul-systemd-reload]) Dependency Archive[/opt/consul/archives/consul-0.7.4.zip] has failures: true
Apr 11 11:59:44 node1 puppet-agent[2304]: (/Stage[main]/Consul::Config/Exec[consul-systemd-reload]) Skipping because of failed dependencies
Apr 11 11:59:44 node1 puppet-agent[2304]: (/Stage[main]/Consul::Config/File[/etc/consul]) Dependency Archive[/opt/consul/archives/consul-0.7.4.zip] has failures: true
Apr 11 11:59:44 node1 puppet-agent[2304]: (/Stage[main]/Consul::Config/File[/etc/consul]) Skipping because of failed dependencies
Apr 11 11:59:44 node1 puppet-agent[2304]: (/Stage[main]/Consul::Config/File[consul config.json]) Dependency Archive[/opt/consul/archives/consul-0.7.4.zip] has failures: true
Apr 11 11:59:44 node1 puppet-agent[2304]: (/Stage[main]/Consul::Config/File[consul config.json]) Skipping because of failed dependencies
Apr 11 11:59:44 node1 puppet-agent[2304]: (/Stage[main]/Consul_mod/Exec[clean invalid consul data]) Dependency Archive[/opt/consul/archives/consul-0.7.4.zip] has failures: true
Apr 11 11:59:44 node1 puppet-agent[2304]: (/Stage[main]/Consul_mod/Exec[clean invalid consul data]) Skipping because of failed dependencies
Apr 11 11:59:44 node1 puppet-agent[2304]: (/Stage[main]/Consul::Run_service/Service[consul]) Dependency Archive[/opt/consul/archives/consul-0.7.4.zip] has failures: true
Apr 11 11:59:44 node1 puppet-agent[2304]: (/Stage[main]/Consul::Run_service/Service[consul]) Skipping because of failed dependencies
Apr 11 11:59:44 node1 puppet-agent[2304]: (/Stage[main]/puppet_agent_run/File[/opt/cdtest/bin/execute-puppet.sh]/ensure) defined content as '{md5}9338f0e1238b4b2b60bb19493799aa36'

**Comment by solarkennedy** [comment]
` Could not execute posix command: No such file or directory - unzip` is your smoking gun. Install unzip.

**Comment by induja0107** [comment]
Thank you.
