### ISSUE TITLE
consul_version fact doesn't always work

### ISSUE THREAD

**Issue by jaxxstorm** [solarkennedy/puppet-consul#339]
The module uses `Facter::Util::Resolution.exec` to determine the consul version. By default, this module stores consul in `/usr/local/bin`. Unfortunately, the `exec` method doesn't include that in the default `$PATH`, so the `consul_version` fact returns `nil`.

Now, you fix this by wrapping the execution with like so:
```
Facter::Util::Resolution.with_env("PATH" => '/usr/local/bin:/usr/bin:/usr/sbin') do
    begin
      Facter::Util::Resolution.exec('consul --version 2> /dev/null').lines.first.split[1].tr('v','')
    rescue
      nil
    end
   end
  end
```

But that doesn't completely solve it. Has anyone else run into this? I only noticed this when trying to run an upgrade to consul with a custom built RPM package (which is a whole other can of worms)

**Comment by solarkennedy** [comment]
Yea it is related to #290, #313.
