### ISSUE TITLE
Consul reload fails without a cluster

### ISSUE THREAD

**Issue by jarro2783** [solarkennedy/puppet-consul#344]
When our hosts can't connect to a cluster, the `consul reload` in `reload_service.pp` fails, which causes our whole puppet run to fail. I think this changed in 0.8.

I reported this in hashicorp/consul#3094, and apparently this is expected behaviour.

Would it be possible to implement the consul reload using the system's service commands instead? I don't consider consul being unavailable a reason to fail the puppet run. I also don't think that setting `$manage_service = false` in special cases is a very good solution for me.

**Comment by solarkennedy** [comment]
Not all init systems support reload. (upstart doesn't, etc)

But yea, this sounds like a difference in opinion. If puppet is configured to get consul up and running, but it can't, should it not provide that feedback in some way?

**Comment by jarro2783** [comment]
Depends on what you mean by `up and running`. I would define the consul program as running to be enough, regardless of whether it joined the cluster or not.

**Comment by jarro2783** [comment]
Actually something else that has just been causing us problems.

1. We are using the EC2 instance ID as the node address.
2. We build AMIs with packer, and build in a node id.
3. Our instances start, and are unable to join the cluster because of having a conflicting node id with some previous instance.
4. Puppet rewrites the node id, but can't restart consul because reload is forbidden when there is no connection to the cluster.
5. Host explodes :(

**Comment by jarro2783** [comment]
Actually ignore my previous, that's a different issue.
