### ISSUE TITLE
Switch from `%{linenumber}` to `%{line}` in v2 branch

### ISSUE THREAD

**Issue by TysonAndre** [solarkennedy/puppet-consul#346]
E.g. for a v2.1.2 release (Also, there's no v2 branch to create a PR against)

I'm using consul 0.7 and puppet-lint 2 in a project, and temporarily disabled this check.

`%{linenumber}` was deprecated in puppet-lint 1.0, and `%{line}` was supported since at least then.

**Comment by solarkennedy** [comment]
Sorry, I'm not really interested in maintaining a v2 branch, especially if the above change is already in master.
