### ISSUE TITLE
Clean out fixtures prior to uploading to forge

### ISSUE THREAD

**Issue by bodgit** [solarkennedy/puppet-consul#349]
I noticed that your Consul module ships with all of the module fixtures intact. This caused a minor problem for me as there are `.git` directories in the fixtures that cause submodule warnings when pushing/pulling this module from git via an r10k workflow, but it also means your module is shipping redundant/unused copies of the stdlib and archive modules so the download size of your module is bigger than it needs to be.

Would you be against adding a step somewhere in the build process to clean these out prior to building the module tarball?

**Comment by solarkennedy** [comment]
Huh. I use https://github.com/voxpupuli/puppet-blacksmith, I figured it would be doing the right thing.

I'll be extra careful on the next release and double check.

**Comment by solarkennedy** [comment]
I've cleaned this up and the most recent release does not have these.
