### ISSUE TITLE
uid/gid

### ISSUE THREAD

**Issue by jfgibbins** [solarkennedy/puppet-consul#353]
Please add to choose uid/gid.  Currently defaults to 999, which is used by several things as default, not least of which is puppet.

**Comment by solarkennedy** [comment]
It doesn't really default to anything, it just uses the first available uid that useradd gives it, but I agree that can conflict if consul is installed first, take 999, and then something else comes along and is pinned to 999.

I would accept a PR, but also I recommend setting your SYS_UID_MIN-SYS_UID_MAX ranges on your system to be outside the range of hand pinned UIDs in puppet to ensure this doesn't happen. (this is what we do at yelp to ensure modules can be installed in any order and ensure that pinned/non-pinned uid/gids never mix)

**Comment by jfgibbins** [comment]
I'll look up how to do a PR and stuff, and give it a shot.  :) I usually like to pin my services, so that they can be added into ldap, and consistent across containers, as well as viewable as a named process on the host, rather than just the number.  And nice job on your project.  Most things I come across on the forge, usually get used for testing and playing only, and then have to be completely rewritten to be of any actual use in my environment.

**Comment by solarkennedy** [comment]
I'm going to close this for now. If you need more control over group/user in this module, DIY and set `manage_group => false` and `manage_user => false` so you can have total control (over the uid or any other parameter).
