### ISSUE TITLE
changes to systemd template

### ISSUE THREAD

**Issue by jfgibbins** [solarkennedy/puppet-consul#354]
I added the following to the systemd template:

ExecStop=<%= scope.lookupvar('consul::bin_dir') %>/consul leave

This allows on service or system shutdown to cleanly leave the cluster.  Probably similar needed on other startup templates as well.

**Comment by solarkennedy** [comment]
Please make a PR if you think the rest of the community would benefit.

**Comment by jfgibbins** [comment]
I will attempt it, though I'm really only familiar with ubuntu/debian.

**Comment by shamil** [comment]
I don't see the reason on doing it in `systemd`. Consul supports this ability out of the box. Read about it in consul configuration guide `https://www.consul.io/docs/agent/options.html#leave_on_terminate`

**Comment by solarkennedy** [comment]
Thanks @shamil. I'm going to stick with that as a recommendation.
