### ISSUE TITLE
cannot update to consul 0.9.0 because of a 'web_ui.zip' package

### ISSUE THREAD

**Issue by khdevel** [solarkennedy/puppet-consul#358]
The module wants to install a *web_ui* package
```
extract_path => "${install_path}/consul-${consul::version}_web_ui",
```
which, since v0.9.0, is not availabe in Hashi's repository.
Please perform the fix in this line (as I assume) [install.pp#L56](https://github.com/solarkennedy/puppet-consul/blob/master/manifests/install.pp#L56)

I could not find any place to make it possible to NOT install the *web_ui* package. Removed *ui_id* did not help in this case. After this Consuls's WebUI was not available.

**Comment by khdevel** [comment]
I used a *ui => true* in my puppet's configuration and removed *ui_dir => ...* section an problem is partly solved. But I think that there should be some notification or part in the code which will not download a *web_ui.zip* package from Hashi's repository.

**Comment by solarkennedy** [comment]
Hmm. With no ui package I guess we should get rid of it for >=0.9 entirely?

Do whatever you've got to do to get things working for you, then please evaluate if you can PR the change for everyone.

**Comment by devcfgc** [comment]
@khdevel Did you manage to fix it? perhaps the ui package has been include somewhere else since 0.9.0.. .

**Comment by boweeb** [comment]
My understanding is that the ui package doesn't exist anymore (>=`0.9.0`) because it's now integrated with consul itself.  To verify, I deployed consul normally without any `ui_*` settings then manually changed the systemd service file to add the `-ui` flag and the ui worked out of the box without installing anything extra.

**Comment by boweeb** [comment]
So a reasonable way to deploy the UI is to just add `-ui` to `extra_options` and not set any `ui_*`.  Perhaps the PR should be more around user experience / documentation.

**Comment by rawleto** [comment]
@khdevel please check #398 out with ui options in the config_hash (see https://github.com/solarkennedy/puppet-consul#web-ui).
