### ISSUE TITLE
Additions to consul_key_value

### ISSUE THREAD

**Issue by houtmanj** [solarkennedy/puppet-consul#359]
Hi,

We have developed our own consul_key_value and would like to get the differences upstream.
Would you be willing to accept them?

Key changes:
- Allows for the specification of the DC for a key/value.
- Does not cache the whole key-value store. But only the prefixes of the keys requested. 
   Assuming:
   - That you are likely to modify some keys in the same directory
   - Caching the whole key-value store can be a heavy and unnecessary operation.
- purge
   Keeps track of the consul keys (with the purge: true) that are managed during this run 
   and deletes the key if they are no longer present as resources in the next puppet run. 
   Works a little like file{"/tmp": type => directory, purge => true} 
   
  This is very handy if your consul use case is similar to "exported resources".
   It uses a special path in consul to keep track of this information across agent runs.

**Comment by solarkennedy** [comment]
* dc: yes
* do we cache currently?
* purge: I thought this came for free with any provider that could list all resources? How does it keep state between runs?

**Comment by lesinigo** [comment]
@solarkennedy @houtmanj usually provider that can list all resources can purge them too, without the need to keep state between runs.

IMHO something similar for consul k/v would be good to have, and it should not rely on state saved between puppet runs, as long as it could work for children of a specific key (eg. "purge foo/bar/baz and all its children"), more or less like the File resource can do for directories and their subdirectories.

**Comment by houtmanj** [comment]
- DC: kewl

- Cache: 
you do, see `list_resources` in https://github.com/solarkennedy/puppet-consul/blob/master/lib/puppet/provider/consul_key_value/default.rb
I was afraid of the performance penalty for recursing the whole key-value store. 
But I just realized that the proper use of ACL's will fix that issue. 

- Purge:
You are both right, a provider that can list all resources could purge unmanaged resources. Just like the file resource can do for a directory.

  But that is not enough in the following scenario.
We have been using consul in part as a replacement for `exported resources`.
F.e. We would write our nagios service check definitions to consul, into a structure not a similar to this: `/nagios/service/<check_hostname>/<service_check_name>`
Our apache proxy would write:
`/nagios/service/xyz.service.google.nl/check_ssl_certificate`

  while the application service would write:
`/nagios/service/xyz.service.google.nl/check_status_page`

  Point being: not all keys in a directory are managed by the same puppet run. 
  So when check_status_page is renamed you need to be very carefull to `ensure => absent` the old key, other wise it will just stay in consul.

  I propose a system where the provider maintains a little state on the system itself. 
  On the next run the provider can use the state to determine that `/nagios/service/xyz.service.google.nl/check_status_page` is no longer part of this puppet run and can be cleaned up. 
  Obviously this behaviour should be optional, but we can make it an argument for consul_key_value.
