### ISSUE TITLE
Support consul-template

### ISSUE THREAD

**Issue by EvanKrall** [solarkennedy/puppet-consul#36]
It'd be nice if this module supported [consul-template](https://github.com/hashicorp/consul-template)

I'm thinking this would be a `consul::template` resource, with `source`, `destination`, `command`, etc. parameters. We'd also need to manage the consul-template service, which will involve making an init script, etc.

**Comment by split3** [comment]
Has there been any traction on this.  I think it would be worth while to have this support self contained in one module without having chained dependencies for this functionality.  It would also be nice to possibly add support for ```consul replicate``` as well.

**Comment by solarkennedy** [comment]
Nope, mostly just waiting for someone with the need to do it.
@EvanKrall with your most recent project, I know you used templates, did you use that consul_template module or did you do something else?

**Comment by split3** [comment]
I'm approaching the need right now so I might add it, I'll wait to hear back from @EvanKrall on what he used.

**Comment by DjxDeaf** [comment]
Is it still planned? an amazing-to-have feature

**Comment by split3** [comment]
I think that this probably make sense as a separate module and I've been using this one:
https://github.com/gdhbashton/puppet-consul_template

**Comment by solarkennedy** [comment]
Yea, I don't think we should re-invent the wheel. I agree that this would be best as a separate module, as it has a different install/config/service/etc.
