### ISSUE TITLE
hiera backend

### ISSUE THREAD

**Issue by houtmanj** [solarkennedy/puppet-consul#367]
I plan to build a hiera 5  backend for consul. 

Since custom hiera backend are implemented as puppet functions, it would make a nice addition to the module.  I plan to use: https://docs.puppet.com/puppet/5.2/hiera_custom_lookup_key.html

There are two lookup scenario's I want to implement.

### Scenario 1
---

A path like:
  - `/prefix/common`
  - `/prefix/nodes/%{::fqdn}`

Will work much the same as normal hiera, expecting a yaml document on those locations, interpreting it and returning data for the requested key. 

### Scenario 2
---

A path like:
  - `/prefix/__KEY__`

Will work a little different. 

1. `__KEY__` will be replaced with the key that is searched.   lookup('lvm_options') will translate to /prefix/lvm_options
2. `/prefix/lvm_options` is a directory in the kv with sub keys. 
3. A recursive lookup on the KV for: `/prefix/lvm_options`
4. Combine that data into a single hash. 
5. Lookups for other data then hashes silently fail for this type of path. 

__Example__

key/value store content:

`/prefix/lvm_options/mysql-lv`
```
---
size: "4GB"
mntpoint: "/var/lib/mysql"
```

`/prefix/lvm_options/log-lv`
```
---
size: "10GB"
mntpoint: "/var/lib/mysql"
```
`/prefix/lvm_options/extra-lvl/abc-lv`
```
---
size: "10GB"
mntpoint: "/var/lib/abc"
```

Results in:
```
mysql-lv:
  size: "4GB"
  mntpoint: "/var/lib/mysql"
log-lv:
  size: "10GB"
  mntpoint: "/var/lib/mysql"
extra-lvl:
  abc-lv:
    size: "10GB"
    mntpoint: "/var/lib/mysql
```

### Consul availability
---
With consul being this thighthly coupled to the puppet infrastructure, its availability becomes critical.
Fixing your consul setup with puppet might become impossible because the hiera lookup breaks the puppet run. 

Because of this I want to implement two silent failures methods:
1. Return cached data when consul is un-available.
2. Return no data when consul is un-available.

The use of either of these methods is configurable and disabled by default. 
The caching will work by keeping a cache file on the puppet masters, that is regurarly updated but only queried when consul is un-available. 

### Consul performance
---
Similar to hiera-http I will implement a `confine-to-keys` config value, that will make sure that consul is only queried for specific keys. 

### YAML vs JSON
---
A configuration value specifies if the consul values will be in json or yaml format. 

### Existing work
---
There are two hiera-consul backends allready available that I know:
- https://github.com/lynxman/hiera-consul
- https://github.com/jsok/hiera-consul

Both of these have not seen recent love and are implemented according to old method (hiera <5).
The idea's and probably code will come from them, credit where credit is due. 

Another good reference is: https://github.com/crayfishx/hiera-http

### Hiera 5
---
I plan to only build support for hiera 5. Available from puppet 4.9

**Comment by solarkennedy** [comment]
Wow this would be fancy. Would such a backend be able to actually reuse any of the code available in this repo? If not then I recommend making a different hiera-consul module specifically for this.

**Comment by houtmanj** [comment]
I plan to reuse that code if I can extract a function that can be used in both implementations. 

I also thought about the a different module, but I would argue that it would go really well together with this module.  It also improves the changes of the code being maintained and people trusting the code if its part of an active project.

**Comment by solarkennedy** [comment]
Ok, sounds good to me (on code reuse).
