### ISSUE TITLE
Idea for approval/rejection:  install-only mode

### ISSUE THREAD

**Issue by Justin-DynamicD** [solarkennedy/puppet-consul#368]
As I continue down my consul journey I find that I'm starting to run into a need where I need the consul module to _only_ handle the installation (download binary and setup service), not configuration (don't commit or manage any config files).  This is due to a possibility of moving encryption and token settings to vault (as opposed to eyaml) and letting consul-template fetch and handle config as a result using templates.

Do we feel this is a feature that would be of value to the larger community (basically add a "install only" or "un-managed" parameter, name up for debate), or this a rather company specific fork?

Simply asking for opinions here.  Depending on answer I may build another fork.

**Comment by solarkennedy** [comment]
Sure, sounds good to me. If possible re-use the install class as much as possible.

**Comment by Justin-DynamicD** [comment]
Install class will still happen, I'm debating just adding to your "manage" parameters with "manage_config".  Seems like the natural place to add a simple true/false.  It would necessarily override the purge_config_dir setting, other than that should be a pretty simple injection.  I _could_ leave that user configurable, but I'm not sure the headache would be worth it (someone accidentally leaving both set to true could be ... interesting).
