### ISSUE TITLE
Changing Consul kv values doesn't seem to have an effect

### ISSUE THREAD

**Issue by dannytrigo** [solarkennedy/puppet-consul#374]
I have tried to test manually changing a kv value after it has been set by the puppet-consul module but it never seems to be changed back by Puppet.
I have added debug code and as far as I can tell, the new value is retrieved from Consul, but then it seems that the flush method is not being called by Puppet, even though the value is different.
Have others had more success with this?

**Comment by solarkennedy** [comment]
It sounds like #363, can you try on master?

**Comment by dannytrigo** [comment]
I tried on master and although better (flush now gets called even though I couldn't figure out why it wasn't before), it still seems to have problems.
Firstly, when the key exists already, it seems `@property_flush[:ensure]` is not set (since its ensure parameter is not changing, so I got:
```
Could not evaluate: ensure attribute is set to unexpected value:
```
So I removed that condition check.  Then I discovered that the value still isn't changed because it seems that in the comparison between `key_value[:value]` and `value` both variables are somehow the new value.

So I removed that check against the current value and it now seems to be working.  Flush only seems to be called when a parameter has changed, so I'm not sure the comparison is actually needed.  Without, puppet is only updating the keys that need updating.

**Comment by dannytrigo** [comment]
@solarkennedy - any opinions on that? Should I open a PR?

**Comment by solarkennedy** [comment]
Yes please. I'll ask @houtmanj to review it (the provider was significantly refactored recently).

**Comment by houtmanj** [comment]
@dannytrigo @solarkennedy I prefer we find out why the underlying assumptions do not behave properly. 
According to the docs the create/delete methods should allways be called, same as the flush method. 
It will very likely also have effect on the major refactoring still pending review and the other providers. 

I currently only have access to a browser and cannot debug the issue any further untill the end of the week. 

@dannytrigo what puppet version are you running? It seems your case is easily reproduced which is nice.

**Comment by dannytrigo** [comment]
Are create/delete always called even if the resource does not need creating, only altering?

I'm using puppet 3.8.7 which is very old and may explain the difference in behaviour.  Can you point me to the docs because I've had a lot of trouble locating good documentation on writing provider plugins.

**Comment by houtmanj** [comment]
Here are some of the resources I found:
- https://puppet.com/docs/puppet/4.10/complete_resource_example.html
- http://garylarizza.com/blog/2013/12/15/seriously-what-is-this-provider-doing/

Turns out I was wrong, the flush method indeed only gets called when there is a change. 
That simplifies matters a great deal.

**Comment by dannytrigo** [comment]
Thanks for the analysis/input. I’ll update the pr according to your feedback. Not sure if other resources need to be modified in a similar way

**Comment by solarkennedy** [comment]
3.2.0 is released. Can you try it out and see if this issue is 100% resolved?

**Comment by dannytrigo** [comment]
Resolved for me
