### ISSUE TITLE
Config validation failed

### ISSUE THREAD

**Issue by maxadamo** [solarkennedy/puppet-consul#383]
I am using consul 1.0.0 and it seems that the validation can be run only against a file having an extension like `.json` or `.hcl`. 
Hence the the temporary file with random extensione fails as following: 
`
Error: Execution of '/usr/local/bin/consul validate /etc/consul/config.json20171119-63488-5w5k49 > /dev/null' returned 1: Config validation failed: Missing or invalid file extension for "/etc/consul/config.json20171119-63488-5w5k49". Please use ".json" or ".hcl".
`

**Comment by solarkennedy** [comment]
I've removed this validation. Please upgrade to 3.2.0
