### ISSUE TITLE
Allow for different consul and consul-ui versions.

### ISSUE THREAD

**Issue by madelaney** [solarkennedy/puppet-consul#384]
With version 0.9+ of consul, there is no analog UI package. The last UI package was 0.8.5. This means that if I try to use consul 1.0.0 (which was original intent), I cannot also setup the UI.

**Comment by bp85** [comment]
can some one address this issue

**Comment by rawleto** [comment]
@madelaney @bp85 using #398 you can install the latest Consul after removing ui_* parameters if any and adding a 'ui => true' option to the config_hash (please follow a link to the details: https://github.com/solarkennedy/puppet-consul#web-ui).
