### ISSUE TITLE
Add hiera wrapper for ACL entries.

### ISSUE THREAD

**Issue by madelaney** [solarkennedy/puppet-consul#385]
Akin to the how we can create `checks` via hiera. I'd like to be able to create ACL entries via the same behavior.

**Comment by solarkennedy** [comment]
We already have this:
https://github.com/solarkennedy/puppet-consul/blob/0e51c7995631e9e5aeb91d27c955f0836f006d61/manifests/init.pp#L7

**Comment by madelaney** [comment]
My bad, I apologize for missing that. Sorry for the spam.
