### ISSUE TITLE
consul_sorted_json for octal notation of file modes

### ISSUE THREAD

**Issue by sts** [solarkennedy/puppet-consul#389]
We are about to [base the puppet consul-template module](
https://github.com/claranet/puppet-consul_template/issues/100) upon consul_sorted_json.rb.

Now consul-template has a `template.perms` configuration setting, which configures filesystem permissions in ocatal notation eg. `0644` which is not a valid integer.

The string match in [consul_sorted_json.rb#85](https://github.com/solarkennedy/puppet-consul/blob/ad0bdb0562d68d106c3b38f4773ab820aa3c140d/lib/puppet/parser/functions/consul_sorted_json.rb#L85) does not take octal representation in account.

**Comment by phaer** [comment]
PR for this issue https://github.com/solarkennedy/puppet-consul/pull/391
