### ISSUE TITLE
Latest version doesn't work with Puppet 3.x (breaking change?)

### ISSUE THREAD

**Issue by madAndroid** [solarkennedy/puppet-consul#394]
Hi,

We're currently moving to Puppet 5.x, and have most of our modules compatible already, but during the transition period we need to be able to support Puppet 3.x as well; recent changes to this module implemented the typing system, and we're seeing failures in Puppet 3.x as a result (even with the future parser enabled).

The particular failure is:
```
Expected parameter 'ui_download_url_base' of 'Class[Consul]' to have type Stdlib::Httpurl, got String at /srv/data/repos/ITV/puppet/puppet-profile-consul/spec/fixtures/modules/profile_consul/manifests/init.pp:206 on node foo.example.com
```

I would expect a change of this nature to have been indicated with a breaking change/major version increment - we restrict the version using `~> 3` so that Librarian Puppet doesn't install unexpected changes. Is there any particular reason the backwardly incompatible changes weren't released as a major version of the module?

**Comment by madAndroid** [comment]
I've just noticed the version requirements listed on the forge show `Puppet >= 4.7.1 < 6.0.0`
We were able to use 3.x of the module until the typing additions... I'm not sure this would be regarded as a breaking change, but it feels like it possibly should have been.

**Comment by solarkennedy** [comment]
Yes, please pin the module to a version you need. 
The breaking change was https://github.com/solarkennedy/puppet-consul/pull/381

Sorry, I should have made another major release to indicate this.
https://github.com/solarkennedy/puppet-consul/blob/master/CHANGELOG.md#v322-2017-12-05

Please pin to 3.2.0.

**Comment by madAndroid** [comment]
Okay, no problem - we'll pin to that version you've suggested.
