### ISSUE TITLE
[critical] consul::check script argument is deprecated

### ISSUE THREAD

**Issue by den-is** [solarkennedy/puppet-consul#395]
https://www.consul.io/docs/agent/checks.html#check-scripts
https://github.com/hashicorp/consul/blob/master/CHANGELOG.md#100-october-16-2017
> Support for Running Subproccesses Directly Without a Shell: Consul agent checks and watches now support an args configuration which is a list of arguments to run for the subprocess, which runs the subprocess directly without a shell. The old script and handler configurations are now deprecated (specify a shell explicitly if you require one). A -shell=false option is also available on consul lock, consul watch, and consul exec to run the subprocesses associated with those without a shell. [GH-3509]

Currently my whole infrastructure is broken because of that:
```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Consul::Check[php-fpm]: has no parameter named 'args' at /etc/puppetlabs/code/...
```

I'm confused:
1. or I can't find open/closed issue regarding this in this repo
2. or I can't find existing fix/workaround for this issue in this module (documentation/code)
3. or finally I'm curious why people didn't report this trivial issue until now.

**Comment by solarkennedy** [comment]
This is the only related PR: https://github.com/solarkennedy/puppet-consul/pull/382

I'm kinda confused as well, it doesn't look like `Consul::Check` ever had args. Is the 500 error from puppet you pasted an attempt to try to use `args` with this module?

It may be deprecated, but not yet an invalid option to use `script`. You are probably the first person to try to use `args` with this module.

**Comment by den-is** [comment]
sorry for confusion:
yes I know that your module doesn't has or ever had `args` arument for `consul::check` - I've included this error output as example of desired behavior.

I can't see where in docs is being said that `script` is valid option.

I'm using a lot of such simple checks:
```
script   => 'systemctl is-active php-fpm',
script   => 'systemctl is-active nginx',
script   => 'systemctl is-active haproxy',
...
```
all of them have failed.

Such config in service/check definition fixes issue:
```
args     => ["systemctl", "is-active", "php-fpm"]
```
------------------
Also I can anticipate possible issue with new http type check https://www.consul.io/docs/agent/checks.html

example which was failing:
```
{
  script   => "test $(curl -s 'localhost/health/ping') = '{\"Status\":\"OK\"}'",
  interval => '10s'
}
```

became:
```
{
  http     => 'http://localhost/health/ping',
  interval => '10s'
}
```

**Comment by solarkennedy** [comment]
Also related to #400 and #404.

We're getting there.

**Comment by den-is** [comment]
if anyone still wants this working right now and right here.
don't use consul::check at all.
make check definition on your own as hash (hiera, manifest or whatever)
and do:
```ruby
  file { "/etc/consul/service_${service_name}.json":
    ensure  => present,
    owner   => 'consul',
    group   => 'consul',
    mode    => '0664',
    content => to_json_pretty($my_service_config_hash),
    notify  => Service['consul']
  }
```
this is much cleaner then depending on third party module, especially if it has 100 arguments to compose simple json file.
left _third-party_ module for consul installs and upgrades.

sorry. no offense.
