### ISSUE TITLE
Consul should not own its config directory

### ISSUE THREAD

**Issue by dekimsey** [solarkennedy/puppet-consul#399]
https://github.com/solarkennedy/puppet-consul/blob/a8ecd9620591660290bb66ffb4ff331be12f0b5f/manifests/config.pp#L95

Typically services don't own their own config directories. I believe the consul config directory should not be owned by Consul as that makes it writable by the consul service. I think it should be root:consul and 750 by default.

The data directory might also fit into this, it's default is 755, I think it should be 750.

**Comment by lesinigo** [comment]
Same applies to the configuration file, if the config directory shouldn't be world-readable nor consul-writable then `config.json` shouldn't be either.
