### ISSUE TITLE
ACLs Managed vs Unmanaged

### ISSUE THREAD

**Issue by aroca** [solarkennedy/puppet-consul#413]
Hi guys,

I am unable to apply rules on a system that already has some manually added ACLs.

> NOTE: This module currently cannot parse ACL tokens generated through means other than this module. Don't mix Puppet and Non-puppet ACLs for best results! (pull requests welcome to allow it to co-exist with ACLs generated with normal HCL)

So that makes be wonder, it is a MUST to handle all ACLs with puppet? No Manually unmanaged ACLs should be used? 

Thanks!

**Comment by solarkennedy** [comment]
Currently yes.

**Comment by aroca** [comment]
Perfect! Thanks for the clarification!  You may close this or if you want just leave it as an enhancement request. Perhaps one day. As you wish!

Thanks again. Cheers
