### ISSUE TITLE
Consul 1.1.0 uses a new key for enableTagOverride

### ISSUE THREAD

**Issue by nealmcq** [solarkennedy/puppet-consul#420]
from Hashicorps docs: 

> For Consul 0.9.3 and earlier you need to use enableTagOverride. Consul 1.0 supports both enable_tag_override and enableTagOverride but the latter is deprecated and has been removed as of Consul 1.1.

**Comment by shamil** [comment]
This is already fixed in #413

**Comment by nealmcq** [comment]
Oh I see. Didn’t see an open issue. Will a release be cut soon that incorporates that fix?

**Comment by bastelfreak** [comment]
I'm going to close this issue since it's fixed in master. I will try to get a new release out soon.
