### ISSUE TITLE
[req] Support setting CONSUL_UI_BETA in an systemd EnvironmentFile instead

### ISSUE THREAD

**Issue by dekimsey** [solarkennedy/puppet-consul#421]
Currently, the module modifies the systemd daemon to enable/disable flags. I'd like to see support instead for an `EnvironmentFile=` directive. That'd make the changes compatible with rpm-based installations like [tomhillable/consul-rpm](https://github.com/tomhillable/consul-rpm).

This would entail moving configs like CONSUL_UI_BETA to /etc/sysconfig/consul instead. As well as updating the systemd template to use the same source instead of re-writing it.

At least for us we have the following consul:: vars set:

```
init_style => unmanaged
install_method => package
manage_group => false
manage_user => false
package_ensure => latest
```

So the rpm we are using manages the systemd service, user, group, and such.

**Comment by bastelfreak** [comment]
Hi @dekimsey, thanks for bringing up this issue. `/etc/sysconfig/` is the default path for configs on centos, but not for other operating systems, so we would need to figure out where to store the configs on debian/arch/ubuntu. Also that may makes it compatible with the linked rpm repo, but that one isn't official. How should we deal with those changes if there is another rpm repo that uses a different path, for example /etc/conf.d/? Also the current systemd unit file is written to /etc and not /usr/lib, so there is no conflict with any rpms.

However, I'm happy to review a pullrequest that enhances the situation if you can provide it.
