### ISSUE TITLE
Performance Raft Multiplier

### ISSUE THREAD

**Issue by Viktorker** [solarkennedy/puppet-consul#426]
Hello everyone on the team,
I am looking to specify the performance of consul server "raft_multiplier" into the config_hash but when I try to build i have failures that this parameter is missing.
Can we somehow import this parameter inside the module?
Many Thanks.

**Comment by bastelfreak** [comment]
Hi @Viktorker, I just added a simple test in https://github.com/solarkennedy/puppet-consul/pull/429/files#diff-850a454de8fd7d1fcd446fb2116ebc94R93, which works. How did you call the module and which error message did you get?
