### ISSUE TITLE
Send SIGHUP to consul agent when new checks/services are detected

### ISSUE THREAD

**Issue by dannykansas** [solarkennedy/puppet-consul#43]
Currently, when a new check or service is added, Consul does not load the check/service unless a "consul reload" is manually run on the node (or SIGHUP sent to the agent process).

Could we start a discussion on the appropriate times to trigger a reload of configuration files (i.e. new check added)?

**Comment by gittex** [comment]
In https://github.com/solarkennedy/puppet-consul/blob/master/manifests/service.pp#L90 there is a Notify on Class[consul::run_service]. Shouldn`t that rather be a Notify on Service[consul]?

**Comment by solarkennedy** [comment]
Notifying the entire class is ok, it should in-turn notify any resources inside, including Service[consul]

**Comment by aj-jester** [comment]
Fixed https://github.com/solarkennedy/puppet-consul/pull/152
