### ISSUE TITLE
Telemetry

### ISSUE THREAD

**Issue by Viktorker** [solarkennedy/puppet-consul#431]
Hello Team,
Thank you very much for the last time.
I am trying to involve into the module the telemetry of consul but I am having some issues that the telemetry is not a parameter.
My config is:
     telemetry => {
      'statsd_address' => 'localhost:9125',
      'prefix_filter' => [
        '+consul.client.rpc',
        '+consul.client.rpc.exceeded',
        '+consul.acl.cache_hit',
        '+consul.acl.cache_miss',
        '+consul.dns.stale_queries',
        '+consul.raft.state.leader',
        '+consul.raft.state.candidate',
        '+consul.raft.apply',
        '+consul.raft.commitTime',
        '+consul.raft.leader.dispatchLog',
        '+consul.raft.replication.appendEntries',
        '+consul.raft.leader.lastContact',
        '+consul.rpc.accept_conn',
        '+consul.catalog.register',
        '+consul.catalog.deregister',
        '+consul.kvs.apply',
        '+consul.leader.barrier',
        '+consul.leader.reconcile',
        '+consul.leader.reconcileMember',
        '+consul.leader.reapTombstones',
        '+consul.rpc.raft_handoff',
        '+consul.rpc.request_error',
        '+consul.rpc.request',
        '+consul.rpc.query',
        '+consul.rpc.consistentRead',
        '+consul.memberlist.msg.suspect',
        '+consul.serf.member.flap',
        '+consul.serf.events',
        '+consul.session_ttl.active',
       ]
     }
Do we have in our plans to include telemetry?

**Comment by Viktorker** [comment]
Wrong configuration from my side! Gratz everyone for their help!

**Comment by bastelfreak** [comment]
Hi @Viktorker, glad that you figured it out! Could you update our README.md with an example that works for you?
