### ISSUE TITLE
Consul version upgrade to 1.2.0

### ISSUE THREAD

**Issue by jayabalan1992** [solarkennedy/puppet-consul#433]
I am using consul as storage backend for vault. By using this module, can I specify new version of consul 1.2.0 instead of 0.7.4 ? Looks like it works fine with the new version as well. Any reason for not upgrading ?

**Comment by solarkennedy** [comment]
Well, like any piece of software, there is a risk of things not breaking. 
Here are some docs:
https://www.consul.io/docs/upgrading.html

**Comment by jayabalan1992** [comment]
@bastelfreak 
I am already using 1.2.0 with no issues so far. Thanks for the response!
