### ISSUE TITLE
Support for service/node "meta" parameters

### ISSUE THREAD

**Issue by sc0rp10** [solarkennedy/puppet-consul#435]
Docs:
https://www.consul.io/docs/agent/services.html
https://www.consul.io/docs/agent/options.html#_node_meta

Error message:
```
Evaluation Error: Error while evaluating a Resource Statement, Consul::Service[foo]: has no parameter named 'meta'
```

**Comment by bastelfreak** [comment]
Hi @sc0rp10, this is currently not implemented. Are you interested in providing a patch for this?

**Comment by sc0rp10** [comment]
hi, @bastelfreak 
Yes, I can try to PR this, but i'm not familiar with puppet tests and can't spent to much time to it.
May you approve PR without tests?

**Comment by bastelfreak** [comment]
We can help out with writing tests. Just create the PR and we will have a look at it.
