### ISSUE TITLE
[4.0.0] service_enable  mask missing

### ISSUE THREAD

**Issue by tuxmaster5000** [solarkennedy/puppet-consul#450]
On systems using systemd the state mask is missing, because it is an boolean.

**Comment by bastelfreak** [comment]
Hi @tuxmaster5000. Can you provide a PR for this?

**Comment by tuxmaster5000** [comment]
But it will  possible break installations, because of the change of the data type.

**Comment by bastelfreak** [comment]
Sorry but I'm not really able to understand the issue here. About which lines are you talking?

**Comment by tuxmaster5000** [comment]
In the file init.pp this part:
```
class consul ( ..
Boolean $service_enable                    = $consul::params::service_enable,
```
To do the change, the boolean must be an Enum, because it can have 3 states.
true, false, mask

**Comment by bastelfreak** [comment]
Can you provide a patch for this? I assume the correct datatype would be `Variant[Boolean,[Enum['mask']]]`
