### ISSUE TITLE
Broken JSON module

### ISSUE THREAD

**Issue by shamil** [solarkennedy/puppet-consul#452]
With latest version (5.x) of this module I can't any longer use `JSON` module.

Seems like after #444 the `JSON` module is no longer usable outside the `consul::sorted_json` function.
Seems like overriding  modules with [The modern Ruby functions API](https://puppet.com/docs/puppet/6.0/functions_ruby_overview.html) causing problems.

**Comment by shamil** [comment]
@solarkennedy  can you please verify or prove me wrong" :smiley:

**Comment by bastelfreak** [comment]
Hi @shamil, do you run in a particular issue? If so which version of puppet/ruby do you use and how do you call the module? I use the latest version in production and it works well.

**Comment by shamil** [comment]
> Hi @shamil, do you run in a particular issue? If so which version of puppet/ruby do you use and how do you call the module? I use the latest version in production and it works well.

The module itself works well, but it cause problems to other puppet functions that make use of `JSON` module.

For example, the following will throw exception, something about no `parse` method in `JSON` module.

```ruby
require 'json'

Puppet::Functions.create_function(:test_func) do
  def test_func(service, options = {})
    JSON.parse('{"foo": "bar"}')
  end
end
```

If I revert consul module to previous version, the above function works **!**

**Comment by solarkennedy** [comment]
Huh. Can you confirm again exactly what version fo ruby+puppet you are using?
We do have this `JSON` module, but I don't know enough ruby to know if there is a namespace collision
https://github.com/solarkennedy/puppet-consul/blob/139a3b7bbf5cabf166ef9e118a5992b63464d783/lib/puppet/functions/consul/sorted_json.rb#L3

**Comment by shamil** [comment]
@solarkennedy yes, that what I meant when mentioning about #444, you extending `JSON` module there. 

I'm running puppet `5.5.8` on ruby `2.4.4p296`

**Comment by bastelfreak** [comment]
I think I just run into this error while using this module + the [vault module](https://github.com/jsok/puppet-vault):

```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Function Call, undefined method `pretty_generate' for Puppet::Pops::Loader::RubyFunctionInstantiator::JSON:Module
Did you mean?  pretty_print (file: /etc/puppetlabs/code/environments/production/modules/vault/manifests/config.pp, line: 30, column: 16) on node vault01.cloud.fabric.mass.systems
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```

**Comment by shamil** [comment]
@bastelfreak, exactly same issue I'm experiencing. If you downgrade the consul module everything will work as expected

**Comment by shamil** [comment]
@bastelfreak any news about this? Do you need me to provide any other information?

**Comment by den-is** [comment]
same here 
Puppet enterprise v2017.3.2

**Comment by surcouf** [comment]
Hi, 
 I've got the same error...

Puppet 4.8
vault 2.0.0
consul 5.0.3
