### ISSUE TITLE
Can we get a new release to forge soon?

### ISSUE THREAD

**Issue by krjensen** [solarkennedy/puppet-consul#469]

**Comment by bastelfreak** [comment]
@solarkennedy can you take care of this? Also I'm a bit confused about the past releases. v5.0.2 is the last release on the forge, but not listed as git tag? 5.0.3 exists as a git tag but not on the forge? Do you upload the modules by hand? If so I suggest switching to releases through travis.

**Comment by solarkennedy** [comment]
I use `blacksmith`, but sometimes I don't get it right still somehow. Let me look into using travis.

**Comment by solarkennedy** [comment]
I've added travis to deploy things and updated the make target to remind me (or you!) on how to do a release next time.
