### ISSUE TITLE
[Feature request] Provide support for Consul 1.4.0+ ACL System

### ISSUE THREAD

**Issue by camskkz** [solarkennedy/puppet-consul#471]
With consul version 1.4.0 the ACL System changed : https://www.consul.io/docs/guides/acl-migrate-tokens.html
Even though the next major releases of Consul will still work with the older ACL system, it would be great to have this feature for this puppet module.

**Comment by bastelfreak** [comment]
@camskkz thanks for reporting this. Are you able to provide a PR for this?

**Comment by camskkz** [comment]
Not at this time, but I will try to find the time to do it

**Comment by SkydiveMarius** [comment]
Just for avoiding double work, we already started working on this topic and will provide a pull request soon.
