### ISSUE TITLE
How to leverage consul_acl resource

### ISSUE THREAD

**Issue by dmcanally** [solarkennedy/puppet-consul#472]
I can't seem to figure out how to leverage the token created with the consul_acl. What I'm trying to do is have every client machine create its own policy with a managment token using consul_acl...

`  consul_acl { $::hostname:
    ensure        => 'present',
    rules         => $rule_hash,
    type          => 'client',
    acl_api_token => $consul_mgmt_token,
  }`

I can see that token in consul itself, and I can see the token in the nacls variable (https://github.com/solarkennedy/puppet-consul/blob/af1e011e4d748f302e8cb826f3da742af037ae24/lib/puppet/provider/consul_acl/default.rb#L90) when puppet runs, but I can't seem to do anything with it.

Is there an existing way to retrieve the token and I'm just missing it?

**Comment by spuder** [comment]
Did you ever figure out how to get the token when using `consul_acl` ?

**Comment by t0xa** [comment]
Hello @spuder and @dmcanally

Did you manage to figure out way how to fetch token from consul_acl resource?

Thanks

**Comment by spuder** [comment]
Yes, `consul_acl` is used by the legacy system. I am using the new acl system so I am using `consul_policy` and `consul_token`. I documented how to use them in the readme

https://github.com/solarkennedy/puppet-consul/pull/487/files

As shown [in this github issue](https://github.com/hashicorp/consul/issues/4977), I am pre-generating tokens and storing them in hiera for every node to ensure idempotence.

**Comment by t0xa** [comment]
Thanks a lot for explanation @spuder. Just to be sure I understand you:

1. Create tokens using `consul_token` resource for each node
2. Manually fetch `SecretID` from Consul UI or via Rest API
3. Store tokens in heira configuration and then configure them as usual

**Comment by spuder** [comment]
Not quite. 

The steps are:

1. Generate a secret id encrypt it and store it in puppet

The secret id is generated with the command `uuidgen`. I have a ruby script that runs `uuidgen` and encrypts the result and stores it in puppet. This happens *before* the vm exists. 

```
    uuid = `uuidgen`
    encrypted_uuid = `eyaml encrypt  --output string --string #{uuid}`
    encrypted_uuid = encrypted_uuid.chomp
    node['profile::consul::agent::tokens'] = {} unless node['profile::consul::agent::tokens']
    node['profile::consul::agent::tokens']['agent'] = encrypted_uuid
    node['profile::consul::agent::tokens']['default'] = encrypted_uuid
```

2. Puppet then creates the `consul_policy` and `consul_token` as shown in the documentation.
