### ISSUE TITLE
option to strip binary

### ISSUE THREAD

**Issue by maxadamo** [solarkennedy/puppet-consul#478]
would you agree to add an option to strip the binary? 
It's just easy: 
```
if ($strip_binary) {
  exec { 'strip_consul_binary':
    path    => '/bin:/usr/bin:/sbin:/usr/sbin',
    command => "strip /var/consul/archives/consul-${consul_version}/consul"
    onlyif  => "file /var/consul/archives/consul-${consul_version}/consul|grep \'not stripped\'";
  }
}
```

**Comment by bastelfreak** [comment]
Hey, could you explain why you need the binary stripped? Is that maybe something that Hashicorp should do during the release process?

**Comment by maxadamo** [comment]
why: because all my C, C++ binaries are already stripped (otherwise I'd need a couple of TB only for the OS) :smile_cat: 
On a serious note, I can understand your objection and in fact, I have raised the same issue to Sensu, and now the new sensu-go binary is stripped (they can even use the compile flag). 
On the other side, if we do it through puppet, we let the user decide whether it must be stripped or not.  
If the user needs the symbols for debugging purpose he can simply set `"strip-binary = false"`
There is pros and there is cons.

**Comment by maxadamo** [comment]
now there is maybe a related question: 
```
du -sh /var/consul/archives/
384M	/var/consul/archives/
```
does the module have an option to purge the old downloads?

**Comment by maxadamo** [comment]
@bastelfreak I'm gonna close this one (this is something I can do and I have already done myself).
