### ISSUE TITLE
New 1.4+ ACL support is not idempotent

### ISSUE THREAD

**Issue by NFarrington** [solarkennedy/puppet-consul#479]
The new support for Consul 1.4+ ACL functionality (added in https://github.com/solarkennedy/puppet-consul/pull/474) appears to not be idempotent.

### Expected Behaviour

```
  consul_policy { "my-policy":
    ensure        => 'present',
    description   => "my-policy",
    rules         => [
      {
        'resource'    => 'key_prefix',
        'segment'     => '',
        'disposition' => 'write',
      },
    ]
  }
```

When Puppet is first run, the policy should be created, and a notice should appear such as `Created Consul ACL policy my-policy with ID 315bab4b-ed75-7537-a722-757abca4d16b`.

On further runs, nothing should happen, and nothing should register as changed.

### Actual Behaviour

When Puppet is first run, the policy is created, and a notice appears, such as `Created Consul ACL policy my-policy with ID 315bab4b-ed75-7537-a722-757abca4d16b`.

However, on the first run and all subsequent runs, other notices also appear, such as `/Stage[main]/Consul_policy[my-policy]/id: defined 'id' as '315bab4b-ed75-7537-a722-757abca4d16b'`, which are registered as a change in Puppet.

### Further Information

This non-idempotent behaviour causes Puppet to report that something has changed every time it runs, even though everything on the Consul side is still exactly the same. Once a policy or token has been created, if the module doesn't change anything on subsequent runs, nothing should be reported as changed.

**Comment by solarkennedy** [comment]
@SkydiveMarius can you take a look at this?

**Comment by SkydiveMarius** [comment]
@NFarrington Thank you for the detailed report!
@solarkennedy I will have a look and will create another pull request.
