### ISSUE TITLE
Feature Request: support special policies like `acl` and `operator` without segment option

### ISSUE THREAD

**Issue by jardleex** [solarkennedy/puppet-consul#482]
Hi,

It seems that the special policies without a segment option are not supported by `consul_policy`.
I wanted to set up a basic [ACL replication](https://learn.hashicorp.com/consul/day-2-operations/acl-replication#create-the-replication-token-for-acl-management) but failed as the module want's to have a `segment` option on each policy.

May you add supporting `acl` and `operator` policies?

Consul: 1.4.2
OS: Ubuntu 16.04
Puppet: 4.10

Thank you, esp. for the added new ACL system support. We're happy that this finally is in.

**Comment by bastelfreak** [comment]
Hi @jardleex, can you provide a pull request for this?

**Comment by jardleex** [comment]
Hi @bastelfreak,
how's about the one from @tmu-sprd?
