### ISSUE TITLE
Puppetforge README and Github README are different

### ISSUE THREAD

**Issue by spuder** [solarkennedy/puppet-consul#485]
This [module on the puppet forge link](https://forge.puppet.com/KyleAnderson/consul) to this github repo, so I assume they are the same module.

Looking at the readme's for version 5.0.3 they are wildly different. 

Specifically regarding how the policy's work. 

Is the link wrong? or is the README out of sync?

**Comment by solarkennedy** [comment]
The link is not wrong.
Yes, the readme for 5.0.3 is different than what is currently on master
https://github.com/solarkennedy/puppet-consul/compare/v5.0.3...master#diff-04c6e90faac2675aa89e2176d2eec7d8
I'll make a new release soon.

**Comment by solarkennedy** [comment]
5.1.0 is now released.
