### ISSUE TITLE
Add support for CNI plugins

### ISSUE THREAD

**Issue by spuder** [solarkennedy/puppet-consul#502]
https://www.nomadproject.io/guides/integrations/consul-connect/index.html#cni-plugins

The CNI plugins are needed for consul connect. 
To install it, run these commands

```
$ curl -L -o cni-plugins.tgz https://github.com/containernetworking/plugins/releases/download/v0.8.1/cni-plugins-linux-amd64-v0.8.1.tgz
$ sudo mkdir -p /opt/cni/bin
$ sudo tar -C /opt/cni/bin -xzf cni-plugins.tgz
```

Should the puppet module install these plugins?

**Comment by bastelfreak** [comment]
Hi. As long as this is an opt-in feature I would be fine with it.

**Comment by spuder** [comment]
Not sure where the best place for this would be. Suggestions welcome. 

For now I'm putting something like this in my profile

```
  file { '/opt/cni':
    ensure => directory,
    owner => 'nomad',
    group => 'nomad',
  } ->
  file { '/opt/cni/bin':
    ensure => directory,
    owner => 'nomad',
    group => 'nomad',
  } ->
  archive { 'cni-plugins':
    path => '/tmp/cni-plugins.tgz',
    source => 'https://github.com/containernetworking/plugins/releases/download/v0.8.1/cni-plugins-linux-amd64-v0.8.1.tgz',
    extract => true,
    extract_path => '/opt/cni/bin/',
    cleanup => true,
    creates => '/opt/cni/bin/flannel'
  } 
```

**Comment by solarkennedy** [comment]
I don't think this should be part of this module. These binaries are not consul-specific, they just happen to be commands that consul could run if you asked it to.

I think it should be a different puppet module.
