### ISSUE TITLE
Compatibility with Puppet 3.6

### ISSUE THREAD

**Issue by vasandr13** [solarkennedy/puppet-consul#503]
We've been using Puppet Version 3.6.2 and configurations is stored at gitlab.
I cloned the module and put it in our repo. 
When I trying to push the changes I get an error:

remote: Validating: modules/puppet-consul/manifests/config.pp
remote: Error: Could not parse for environment production: Syntax error at 'Hash'; expected ')' at line 23

Could you please suggest something to resolve this issue?

Thank you.

**Comment by bastelfreak** [comment]
Hi. Your puppet version is end of life since years. it's not supported anymore. Based on that, we dropped support for this version in this module. Our metadata.json says that you need at least Puppet 4.7.1 (which is also EOL, Puppet 6 is the current one).
