### ISSUE TITLE
Service port gets quoted with a puppet 6.10 catalog server and consul rejects it

### ISSUE THREAD

**Issue by rtkennedy** [solarkennedy/puppet-consul#526]
With this service configuration:

```
  consul::service { 'node_exporter':
    address => $::hostname,
    checks  => [
      {
        'http'     => 'http://localhost:9100',
        'interval' => '5s',
      }
    ],
    port    => 9100,
    tags    => $consul_tags;
  }
```

consul module version 6.0.0, and a puppet 6.10 catalog server I get a service json file with a quoted port number:

```
{ "service": {"address":"cadws002","checks":[{"http":"http://localhost:9100","interval":"5s"}],"enable_tag_override":false,"id":"node_exporter","meta":null,"name":"node_exporter",**"port":"9100"**,"tags":["node_exporter","metrics","eng"],"token":null}}
```

which results in a consul error: `* 'service.port' expected type 'int', got unconvertible type 'string'`

The sorted_json() function doesn't seem to do this when the same code is run through a puppet 5.5 catalog server.

**Comment by rtkennedy** [comment]
Additionally, the major version of the client doesn't matter. A 5.5 client pointed at a 6.10 catalog server will get the stringified integer, and a 6.10 client pointed at a 5.5 catalog service will get a bare integer.
Removing 'Integer' from 'when Integer, Float, TrueClass, FalseClass' in sorted_json allows it to fall through and not get quoted - though I'm still not sure why 5.5 wasn't hitting the same code path unless it was stringifying it on the way in and having it end up in the else clause.

**Comment by rtkennedy** [comment]
It's looking more like code to turn on the quoted boolean for everything inside node_meta|meta|tags hashes in the 2 sorted*generate functions is instead turning it on for everything that happens after it in the loop.

**Comment by helenes-r7** [comment]
I'm running into this issue as well

**Comment by bastelfreak** [comment]
Hi people. I need to say that I'm unable to reproduce this. I'm running version 6.1.0 of this module with puppetserver 6.12.1 and puppet agent 6.17.0. example consul code:

```puppet
    consul::service { 'node_exporter':
      checks  => [
        {
          name     => 'node_exporter health check',
          http     => 'http://127.0.0.1:9100',
          interval => '10s',
          timeout  => '1s'
        },
      ],
      port    => 9100,
      address => $consul_address,
      tags    => ['node_exporter'],
    }
```

results in:

```json
{
    "service": {
        "address": "***",
        "checks": [
            {
                "http": "http://127.0.0.1:9100",
                "interval": "10s",
                "name": "node_exporter health check",
                "timeout": "1s"
            }
        ],
        "enable_tag_override": false,
        "id": "node_exporter",
        "name": "node_exporter",
        "port": 9100,
        "tags": [
            "node_exporter"
        ]
    }
}
```

**Comment by rtkennedy** [comment]
The simple fix of excluding Integer from the list fixes the quoted port issue, but it does not fix any more complicated configs with nesting because the recursion causes quoting to get turned on for all enclosed parameters, even if they should not be quoted. I tried with https://github.com/solarkennedy/puppet-consul/pull/527 but never pushed it over the finish line with an RH6 TravisCI issue that I could not replicate locally.

**Comment by helenes-r7** [comment]
I was running version 6.0.1 of the module, with puppetserver 6.12.0 and puppet agent 6.17.0.

After upgrading to version 6.1.0 of the module I'm now getting the proper, unquoted integer for the port number.
```
# cat /etc/consul/service_node-exporter.json | jq
{
  "service": {
    "address": "host.example.com",
    "checks": [
      {
        "http": "http://localhost:9100",
        "interval": "10s"
      }
    ],
    "enable_tag_override": false,
    "id": "node-exporter",
    "name": "node-exporter",
    "port": 9100,
    "tags": [
      "node_exporter"
    ]
  }
}
```

I should have made sure I was on the latest version of the module. Thank you @bastelfreak and @rtkennedy !
