### ISSUE TITLE
What do I need to do to to get the nslcd service started before the Consul service

### ISSUE THREAD

**Issue by induja0107** [solarkennedy/puppet-consul#531]
I need to change the consul service definition so that the nslcd service is started before consul so that applications running on the boxes don't have issues starting because consul is not yet up.

What's the best way to accomplish this?

Should I fork solarkennedy/puppet-consul module and change the consul.service.erb template or is there a config parameter i can pass to be added to the consul.service? 

Thanks in advance.

**Comment by solarkennedy** [comment]
There are lots of ways to change (override) systemd behavior. See if you can do it via local overrides:
https://askubuntu.com/a/659268

**Comment by induja0107** [comment]
Thank you!
