### ISSUE TITLE
No obvious support for setting headers for inline service checks

### ISSUE THREAD

**Issue by chrisjohnson** [solarkennedy/puppet-consul#542]
Code:
```
...
  ::consul::service { "test":
    port   => 443,
    checks => [
      {
        name => "Heartbeat check for ${::app_id}-${::app_name}.testing.site.com",
        http => "https://127.0.0.1:443/_heartbeat",
        tls_skip_verify => true,
        method => "GET",
        header => { Host => ["${::app_id}-${::app_name}}.testing.site.com"] },
        interval => "1s",
        timeout => "5s"
      }
    ],
  }
```

Error:

```
Error while evaluating a Resource Statement, Consul::Service[test]: parameter 'checks' index 0 entry 'header' expects a Data value, got Hash at /etc/puppetlabs/code/environments/deployme_modern_consul/site/profile/mani
fests/test.pp:7
```

The expected JSON should be:

```
...
    {
      "name": "test",
      "port": 443,
      "checks": [
        {
          "name": "Heartbeat check for rx3-test.testing.site.com",
          "http": "https://127.0.0.1:443/_heartbeat",
          "tls_skip_verify": true,
          "method": "GET",
          "header": {
            "Host": [
              "rx3-test.testing.site.com"
            ]
          },
          "interval": "1s",
          "timeout": "5s"
        }
      ]
    }
...
```

We are using an older version of puppet and only using 5.1.0 of the module, however looking at the master branch, it doesn't seem much has changed in this area.

If at all possible, back-porting the fix to the 5.x line would be greatly appreciated :)

**Comment by chrisjohnson** [comment]
It looks like using this form works `        header => { "Host" => ["${::app_id}-${::app_name}}.testing.site.com"] },`

So maybe this ticket should just be, add an example header config? It was tough to figure this out and we basically lucked into it

**Comment by solarkennedy** [comment]
I think just this issue is an OK way to document this.

It is puppet, so a bare `Host` in part of a hash... well I don't know what it will do.
We know what in the end this needs to be a string in the file, so quoting it explicitly is a good thing I think.

**Comment by chrisjohnson** [comment]
That's fine, I mean updating the readme because there is no mention of how
to handle non-scalar keys anywhere. An issue isn't really documentation

**Comment by solarkennedy** [comment]
I don't think we need this kind of documentation on the README. This is just general puppet knowledge about putting quotes around strings right? https://puppet.com/docs/puppet/6.17/lang_data_hash.html#syntax

> Hash keys can be any data type, but generally, you should use only strings. Put quotation marks around keys that are strings.

**Comment by chrisjohnson** [comment]
None of the other fields require quotes. It is a special circumstance that
only applies to this singular field

**Comment by chrisjohnson** [comment]
Sorry, what I mean is that this particular field differs from the rest. I don't really see the harm in adding to the documentation for those of us who arent puppet experts. But if you think it's harmful then I guess that's your call

**Comment by solarkennedy** [comment]
You are right, it isn't obvious which keys are arguments to a module and which keys are actually k/v strings in a hash.
I would accept a PR.

**Comment by chrisjohnson** [comment]
https://github.com/solarkennedy/puppet-consul/pull/543 Thank you!

**Comment by chrisjohnson** [comment]
Resolved
