### ISSUE TITLE
Can not download the archive. need to allow insecure access to download for archive

### ISSUE THREAD

**Issue by alexhill050392** [solarkennedy/puppet-consul#553]
When downloading though a http proxy, we get the following error:

Error: Could not set 'present' on ensure: SSL_connect returned=1 errno=0 state=error: certificate verify failed at 41:/etc/puppetlabs/code/environments/tooling/modules/consul/manifests/install.pp
Error: Could not set 'present' on ensure: SSL_connect returned=1 errno=0 state=error: certificate verify failed at 41:/etc/puppetlabs/code/environments/tooling/modules/consul/manifests/install.pp
Wrapped exception:
SSL_connect returned=1 errno=0 state=error: certificate verify failed
Error: /Stage[main]/Consul::Install/Archive[C:\ProgramData\consul/archives/consul-1.7.2.zip]/ensure: change from absent to present failed: Could not set 'present' on ensure: SSL_connect returned=1 errno=0 state=error: certificate verify failed at 41:/etc/puppetlabs/code/environments/tooling/modules/consul/manifests/install.pp

**Comment by solarkennedy** [comment]
You need to add your proxy's cert to your authorized CAs, not disable ssl verification and making it less secure for everyone.
