### ISSUE TITLE
HCL Config Support

### ISSUE THREAD

**Issue by bogdankatishev** [solarkennedy/puppet-consul#557]
Hello,

I could not find any issues that mentioned support for HCL config files.

As I can see the only supported output for config is JSON. Is there a specific reason why HCL output is not implemented yet, or can I make a new PR which adds support to choose from JSON/HCL output?

**Comment by solarkennedy** [comment]
Well, puppet is a program, outputting json for another program to consume.
HCL is a human-friendly language, so I don't see a need for supporting that output.
Puppet DSL is the human friendly language here.
We don't need anything more than `thing.toJSON` in the puppet provider code for our communication with consul to work.
