### ISSUE TITLE
New Home Attribute on consul user resource breaks our puppet runs.

### ISSUE THREAD

**Issue by bogdankatishev** [solarkennedy/puppet-consul#559]
This merge https://github.com/solarkennedy/puppet-consul/pull/550 breaks our Puppet runs on our current Consul Agents.

```
Error: Could not set home on user[consul]: Execution of '/usr/sbin/usermod -d /opt/consul/data consul' returned 8: usermod: user consul is currently used by process 894
Error: /Stage[main]/Consul::Install/User[consul]/home: change from '/home/consul' to '/opt/consul/data' failed: Could not set home on user[consul]: Execution of '/usr/sbin/usermod -d /opt/consul/data consul' returned 8: usermod: user consul is currently used by process 894
```

As far as I can see, many popular Puppet Modules avoid the User resource, or when they use them, they do not set the home attribute.

How could this be resolved cleanly?

**Comment by solarkennedy** [comment]
Oh man, I didn't expect that change not work with a running process. Hmm :(

**Comment by genebean** [comment]
I was just coming to report the same issue...

**Comment by bplunkert** [comment]
I am seeing the same issue preventing consul deployment on 7.0.0.
