### ISSUE TITLE
Bump to hashicorp/consul  GitHub version e9615c50e6

### ISSUE THREAD

**Issue by EvanKrall** [solarkennedy/puppet-consul#58]
hashicorp/consul &middot; GitHub version e9615c50e6 released at January 2, 2015 at 12:48AM

**Comment by EvanKrall** [comment]
my IFTTT trigger didn't quite work as intended. I thought this would only trigger on new "releases", not all commits.

**Comment by solarkennedy** [comment]
Hehehehe
