### ISSUE TITLE
Path to /home/kyle is hard coded, somewhere

### ISSUE THREAD

**Issue by bhourigan** [solarkennedy/puppet-consul#65]
I'm trying to install the consul module on my OSX Laptop using librarian-puppet, the puppet module install command fails citing an non-existent path of /home/kyle. 

Librarian puppet is generating the following module install command: https://gist.github.com/bhourigan/6fc71c3506fdd9cede81

Output of running it with --debug:
https://gist.github.com/bhourigan/8c3b9c1e72ad54e4fc66

I must be missing something important, as I can't find a telling location of the substrings 'home', or 'kyle'. Running puppet module installer under dtruss did give me more information about the full path, but alas, it has not given me more insight into where the problem lies.

Debug command: sudo dtruss -b 32m -f <command in gist 6fc71c3506fdd9cede81>

Interesting snippit (full output available upon request)
65195/0x3bfd22:  symlink("/home/kyle/Projects/puppet_modules/puppet-consul\0", "KyleAnderson-consul-0.4.2/spec/fixtures/modules/consul\0")               = 0 0

I'm running ruby 2.0.0p481, and according to https://docs.puppetlabs.com/guides/platforms.html#ruby-versions it is supported.

**Comment by gozer** [comment]
Looks like there is a dangling symlink in the released archives for that module, but me too.

**Comment by bhourigan** [comment]
Good catch! It's not present in the git checkout, but when I download the .tar.gz from puppet forge I see the following:

22886459        8 lrwxr-xr-x    1 bhourigan        staff                  48 Oct 28 23:26 ./spec/fixtures/modules/consul -> /home/kyle/Projects/puppet_modules/puppet-consul

**Comment by solarkennedy** [comment]
Whoops. Ug :(
Um. 

I've built 0.4.5? tar -tzf shows no symlink?

**Comment by solarkennedy** [comment]
I'm going to close this as I think it is fixed in the latest release.

**Comment by bhourigan** [comment]
Thanks!
