### ISSUE TITLE
Support for Consul 0.5.0 and multiple check configuration

### ISSUE THREAD

**Issue by chrisleavoy** [solarkennedy/puppet-consul#73]
I just reviewed the Consul 0.5.0-rc1 change log and it looks like there will be a few changes that will require changes in puppet-consul.  Some quick notes:

 * 'consul::service' will need to be updated as the checks property for services is now an array instead of a hash.
 * 'consul::check' will also need updates for the new HTTP check type as well as optional service_id property.

**Comment by solarkennedy** [comment]
Cool. I've released 0.4.6 to the forge and added a compatibility section.

The next version/tag of this module will be 0.5.0 to be compatible with Consul 0.5.0!

**Comment by solarkennedy** [comment]
Believe it or not, this module does have an acceptance test suite, I would love to see us TDD our way towards 0.5.0 compatibility.

**Comment by EvanKrall** [comment]
These sound like they could cause us to be backwards-incompatible. Should we bother maintaining a branch that's compatible with 0.4, or just expect people to upgrade?

**Comment by solarkennedy** [comment]
Na. If people are on .4 they can use a release from the .4 series, otherwise they can be on .5 or master.

**Comment by centromere** [comment]
Has there been any progress towards 0.5.0?

**Comment by solarkennedy** [comment]
Na :(

**Comment by jelmerk** [comment]
Any ETA on when a 0.5.0 compatible version will be released?

**Comment by solarkennedy** [comment]
There is #94, but needs a little TLC.
Patches welcome?

**Comment by split3** [comment]
Do you have a list of additional known items that need to make this compatible? I'd be happy to provide some pull requests.

**Comment by solarkennedy** [comment]
As far as I know, the list at the top of this issue is it. For the most part things are backwards compatible, but I'm not running 5.0 in production yet.

**Comment by split3** [comment]
I added a pull request #98 with the additional options for checks along with unit tests for it.  I will work on the additional service options as well.

**Comment by split3** [comment]
I went ahead and finished up the service portions and move all the validation logic into a function since it needed to really be used in multiple locations by consul::check and consul::service with the checks array.  The pull request is located #99.

I added several tests to ensure that things are getting handled properly but please double check to see if anything was missed or more tests are wanted.

**Comment by solarkennedy** [comment]
This in place.
I'm not using .5 in production yet, so we'll have to wait for bug reports if anything crucial is missing.
