### ISSUE TITLE
How to uninstall consul from node?

### ISSUE THREAD

**Issue by kostyrevaa** [solarkennedy/puppet-consul#79]
How do you get rid of it now?

**Comment by solarkennedy** [comment]
We don't really have any defined way to "remove" everything the module installs.

If you used a package you can say `package_ensure => absent`, but this will not remove everything.

If you make a class to remove *all* resources this module installs can you PR?

**Comment by kostyrevaa** [comment]
definitely)
but I'm not sure when I get free time to do it

**Comment by shuron** [comment]
I'm not sure if it's puppet's approach to remove to much things.
