### ISSUE TITLE
passingonly needs to be a boolean for watch type

### ISSUE THREAD

**Issue by garethr** [solarkennedy/puppet-consul#97]
## Problem

The documentation contains the example:

```puppet
consul::watch { 'my_watch':
  ...
  passingonly => 'true',
}
```

This results in a config file like:

```json
{
  "watches": [
    {
     ...
     "passingonly": "true"
    }
  ]
}
```

This will in turn cause an issue for Consul starting with an error similar to:

```
==> Failed to parse watch (map[string]interface {}{"passingonly":"true", "handler":"/usr/bin/runpuppet.sh"}): Expecting %!s(MISSING) to be a boolean
```

Changing the config file by hand to the following fixes the problem.

```json
"passingonly": true
```

Passing in the value to Puppet as a boolean also fixes the problem.

```puppet
consul::watch { 'my_watch':
  ...
  passingonly => true,
}
```

## Fix

* Docs could be updated to show working values
* Manifests could validate values being passed are booleans

## Additional thoughts

* This may affect other types which take booleans, and currently show passing strings in the READM.
* This might be version specific, just in case:

```
consul --version
Consul v0.4.1
Consul Protocol: 2 (Understands back to: 1)
```

**Comment by solarkennedy** [comment]
Yes please. PR?

**Comment by garethr** [comment]
I'll take a look when I get a moment, although it might be a week or so.
